### ISSUE TITLE
Auto-Picking problem

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-relion#101]
Dear all,

I tried to use a volume as Autopicking-reference (I know this sounds rare, but reading the help)

"Input references (SetOfAverages) for auto-pick. 

Note that the absolute greyscale needs to be correct, 
so only use images with proper normalization. From Relion 3.0 it is also possible to provide a 3D volume which projections will be used as references."

Thus, if a volume is introduced in the reference, next window message appears
 Thanks in advance

Sorry, this is embarrassing: the validation is failing due to a programming mistake. This should not happen. Check out the message. It might help to workaround this bug. We'd really appreciate if you report this to: scipion@cnb.csic.es
Error: AttributeError
Description: 'Volume' object has no attribute 'isOddX'
Traceback:
 File "/home/vilas/software/scipion/pyworkflow/protocol/protocol.py", line 1817, in validate
   childErrors = self._validate()  File "/home/vilas/software/scipion/software/lib/python2.7/site-packages/relion/protocols/protocol_autopick_v2.py", line 540, in _validate
   if self.getInputReferences().isOddX():

**Comment by azazellochg** [comment]
@Vilax , it's not working at the moment, the 3d references support will be available together with relion 3.1 support, in the next plugin version.

**Comment by delarosatrevin** [comment]
@Vilax In the meantime, you can project the volume into 2D gallery (I can't remember the exact name of the Xmipp protocol) and the use these 2D projections as reference for picking in Relion.

**Comment by Vilax** [comment]
@azazellochg Thanks for your reply, we will wait until next release :)

@delarosatrevin thank you, that was exactly was I did :) the difference is that I imported references from classes

**Comment by azazellochg** [comment]
Fixed in 6cab6b8648a482a141a1fee4a26c20d57d63ebd6
