### ISSUE TITLE
Bayesian polishing fails at createOutput step

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-relion#102]
Hi!

**Describe the bug**
Protocol runs until the end (relion stuff seems to work fine) but the createOutputStep fails after a while

01901:   STARTED: createOutputStep, step 3
01902:     2019-09-22 14:19:59.647630
01903:   Traceback (most recent call last):
01904:     File "/home/virus/SOFTWARE/SCIPION/scipion2/pyworkflow/protocol/protocol.py", line 186, in run
01905:       self._run()
01906:     File "/home/virus/SOFTWARE/SCIPION/scipion2/pyworkflow/protocol/protocol.py", line 237, in _run
01907:       resultFiles = self._runFunc()
01908:     File "/home/virus/SOFTWARE/SCIPION/scipion2/pyworkflow/protocol/protocol.py", line 233, in _runFunc
01909:       return self._func(*self._args)
01910:     File "/home/virus/SOFTWARE/SCIPION/scipion2/software/lib/python2.7/site-packages/relion/protocols/protocol_bayesian_polishing.py", line 302, in createOutputStep
01911:       itemDataIterator=rowIterator)
01912:     File "/home/virus/SOFTWARE/SCIPION/scipion2/pyworkflow/em/data.py", line 936, in copyItems
01913:       else next(itemDataIterator)
01914:   StopIteration
01915:   Protocol failed: 
01916:   FAILED: createOutputStep, step 3

**To Reproduce**
We can reproduce it here with our data everytime we continue the protocol

**Expected behavior**
do not fail

**Desktop (please complete the following information):**
 - Scipion version: [e.g. 2.0]
 - Relion plugin version [e.g. 1.0.7] we've just updated it and run it.

**Comment by pconesa** [comment]
I can either send files or add print lines where you indicate to know more, let me know.

**Comment by azazellochg** [comment]
@pconesa did you provide correct input movies (output from movie alignment protocol?) Did you use motioncor or relion to align movies? Could you attach shiny.star output from the protocol?

**Comment by pconesa** [comment]
Not sure, I'll check on monday with the user

**Comment by pconesa** [comment]
@mcallende will join github and will anwser this, I'll be reading in case she needs help.

**Comment by carolinaallende** [comment]
> @pconesa did you provide correct input movies (output from movie alignment protocol?) Did you use motioncor or relion to align movies? Could you attach shiny.star output from the protocol?

Hi @azazellochg,
-Yes, I did provide movies aligned from motioncor.
-Attached you can find the shiny.star output file

Let me know once you have checked it, thanks in advance.

[shiny.star.zip](https://github.com/scipion-em/scipion-em-relion/files/3680764/shiny.star.zip)

**Comment by azazellochg** [comment]
Hi @carolinaallende , shiny.star looks okay to me. Could there be a mismatch between input particles and output ones? You have 136988 output particles, how many were did you input?

**Comment by carolinaallende** [comment]
Hi @azazellochg, I input a total of 271489. I did not notice about that mismatch. Although I do not know what does that mean at all. Isn't the Bayesian polishing been executed in all particles then?

**Comment by carolinaallende** [comment]
And why this would be related with the creation of the OutputStep?

**Comment by azazellochg** [comment]
Output step is updating input particles, catching the new polished filename from output.
Yes, it should be executed on all particles. Could you post or attach full run.stdout here?

**Comment by azazellochg** [comment]
The only reason I can think it discarded half of data because it couldn't find the corresponding movies, but maybe it's smth else.

**Comment by pconesa** [comment]
Any local "action" you want me to do? @azazellochg

**Comment by azazellochg** [comment]
@pconesa I need to see log files first

**Comment by pconesa** [comment]
Ok, let me know if you need some local "eyes".

**Comment by carolinaallende** [comment]
[runstdout.txt](https://github.com/scipion-em/scipion-em-relion/files/3690257/runstdout.txt)

Here I attach the runsdout!

**Comment by azazellochg** [comment]
There we go:
```
00048:    - The following micrographs are missing:
00049:          Runs/000744_ProtImportMovies/extra/MyBook1_GridSquare_19129675_Data_FoilHole_19147738_Data_19142478_19142480_20190621_064703-346374.mrc
00050:          Runs/000744_ProtImportMovies/extra/MyBook1_GridSquare_19129675_Data_FoilHole_19147738_Data_19142582_19142584_20190621_064821-346377.mrc
...
```

**Comment by pconesa** [comment]
I guess that we (most of the scipion protocols) should prevent this from failing. I understand why but the fact is that relion didn't failed but we did. @delarosatrevin , is there any way to make the createOutput robust to "missing items" with the actual "output creation tools/helpers"?

**Comment by pconesa** [comment]
@azazellochg can you think of any hack to continue the protocol and get the output?

I guess we can tweak the input set to have only the existing movies.

**Comment by azazellochg** [comment]
I am working on a quick fix, stay tuned

**Comment by pconesa** [comment]
Great!, @carolinaallende will probably run it again since half of her particles didn't make it into the output. (She had the movies in 2 external HD and one was not mounted).

So, there is no need to rush it for her. Still I think it would be nice to tolerate missing items from scipion, if make sense, or at least the binary behind didn't failed.

I'm closing this. Many thanks @azazellochg

**Comment by carolinaallende** [comment]
@azazellochg  thanks for your comments and 'diagnostic'. Revising the input data I realised that one of the hard discs containing the movies was not correctly mounted...  that is why half of the data was not found when importing the motioncor aligned movies... I will run the missing data again, i expect that now it will work!

Thank you very much @azazellochg

**Comment by carolinaallende** [comment]
Thanks @pconesa for your support and suggestions too!!!

**Comment by azazellochg** [comment]
Thank you both!

I will make a proper fix then!

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk
