### ISSUE TITLE
motioncor: add batch options

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#104]
### Some possible improvements:
* Add batch options: this will require either a refactoring of the base class to support this or that we implement it ourselves for this protocol by re-implementing some of the base class methods. 
* We can re-implement the Compute-PSD method to use and compose the already generated PSD from Relion, without calling Xmipp again to compute them.

**Comment by delarosatrevin** [comment]
Will be addressed in a more general issue
