### ISSUE TITLE
3D Auto-refine unexpected fail

### ISSUE THREAD

**Issue by gilcantero** [scipion-em/scipion-em-relion#109]
Hello, I am experiencing some problems regarding the 3D auto-refine protocol of Relion 3.0 in Scipion. When I run it with classes which come from a Relaxed Symmetry 3D Classification protocol (https://github.com/OPIC-Oxford/relion-relax) some classes failed during first iteration of the refinement. The error which appears is the following:

Expectation iteration 1
00141:   000/??? sec ~~(,_,">                                                          [oo]00142:   ERROR: CudaCustomAllocator out of memory
00143:    [requestedSpace:             587801088 B]
00144:    [largestContinuousFreeSpace: 494327808 B]
00145:    [totalFreeSpace:             494327808 B]
00146:   (90112B) (91648B) (587801088B) (1175602176B) (1175602176B) (1175602176B) (1175602176B) (2351204352B) (27990528B) (512B) (512B) (512B) (5632B) (5632B) (5632B) (5632B) (5632B) (5632B) (5632B) (5632B) (5632B) [494327808B] = 8163966464B
00147:   in: /home/virus/SOFTWARE/SCIPION/scipion_plugin/scipion/software/em/relion-3.0/src/acc/cuda/custom_allocator.cuh, line 546
00148:   --------------------------------------------------------------------------
00149:   mpirun noticed that process rank 2 with PID 25532 on node aries exited on signal 11 (Segmentation fault).

It had this error when particle boxes are too big, but in these cases, box sizes are 100-150 pixels (I had worked with boxes up to 450 pixels) and less than 35,000 particles in all cases. Besides, those refinements running correctly has sometimes more particles than those failing, other times less particles... This has occurred with different projects as well.  In order to bypass the problem I have tried to make a subset with the original particles contained in that classes and refine them after assigning the angles to the original particles (it solved the problem in some cases and not in others). I have also tried to reextract those particles and refine them after giving them the angles (again, it does not work always).

I had used this methodology previously and I did not have problems until now.

Does anyone have any clue what could be happening?

Thank you in advance,
David.

**Comment by gilcantero** [comment]
Hi Jose Miguel,
I am using 3 MPIs, 1 Thread, and two Nvidia Geforce GTX 1080 graphic cards. I have used this settings for other refinement with bigger boxsizes (the maximum I have tried is 450 pixels) and higher number of particles (~100k) for I2 Symmetry. For C1 symmetry (where I am having the issues now) I have also tried bigger boxsizes and number of particles (for example a I have a case with a size of 150 pixels and 32k particles that run fine but another class from the same classification with the same box and  20k particles failed)

**Comment by gilcantero** [comment]
GPUs have 8Gb memory each one

**Comment by delarosatrevin** [comment]
Hum...this configuration sounds good.
And it is weird that it fails for another case that seems smaller.
I'm not sure if there is any class-dependent thing that generates more
memory used in the GPU.
Are you using the --maxsig parameter?

Just to rule out possible issues, was this job running alone in the machine
at that time?

**Comment by gilcantero** [comment]
No, I have not used  the --maxsig parameter, I will try.
Yes, It was the only job running I checked with nvidia-smi to be sure, should I check it other way?

**Comment by delarosatrevin** [comment]
You should use:
--maxsig X
where X is a integer value (e.g 25)

**Comment by delarosatrevin** [comment]
@gilcantero Can we close this issue?

**Comment by gilcantero** [comment]
Yes, with your suggestion the problem was solved.
