### ISSUE TITLE
Implement protocol wrapping flex_analyse to subtract one of the bodies after MultiBody

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-relion#110]
Allow to subtract one of the bodies after relion - multibody refinement as described
in section 3.5 here: ftp://ftp.mrc-lmb.cam.ac.uk/pub/scheres/multibody_protocol.pdf

It can be implemented as a separated protocol, which input might be the multibody protocol and the selection of the body that should be kept. The output should be a set of particles with the signal from all bodies subtracted except the selected body.

**Comment by azazellochg** [comment]
Subtraction should now be done in subtraction protocol, not by flex_analyse

**Comment by azazellochg** [comment]
done in #352
