### ISSUE TITLE
Removed older binary versions

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-relion#115]
As moving into Relion 3.1, we are planning to deprecate support for 2.0, thus removing also binaries installation.

@JuhaHuiskonen do you still need Relion1.4 binary? We are planning to remove that one as well from the installation options.

**Comment by azazellochg** [comment]
1.x is gone, 2.x will be gone in Scipion 3 / relion 3.1 release. We do not have resources to support this.

**Comment by JuhaHuiskonen** [comment]
We have no need for Relion 1.4 binary - LocalRec plugin is independent and doesn't require Relion binaries
