### ISSUE TITLE
Reconstruction issues when using Relion2 and 3

### ISSUE THREAD

**Issue by gilcantero** [scipion-em/scipion-em-relion#116]
Good afternoon, 
When I run a 3D Classification using Relion 2 (more precisely a modification of it), I select the model I like (which is downsampled three times) and then I carry out an intersection with the original particles to have the particles from that class but at the original pixel size. I assign the angles from the classification to the non-downsampled particles and run an auto-refine or a new 3D classification (using relion 3), and in both cases the models are worse than the original. If I just reconstruct with the angles applied, the reconstruction is also quite bad, I checked the angle assignment and it is ok. Might it be a problem related with using two different Relion versions?

Thank you in advance

**Comment by delarosatrevin** [comment]
Hi,

There is a caveat when you use 'scipion - extract coordinates' (not sure if
you used it).
If you apply the computed shifts (from 2D or 3D classification/refinement)
then the new
coordinates are shifted, so you should not assign previous alignment in
that case.

Best,
Jose Miguel

**Comment by azazellochg** [comment]
I think the better way is to extract coordinates without applying shifts and then use assign alignment.

**Comment by gilcantero** [comment]
Hi, I have not used 'scipion - extract coordinates'. I did 'scipion - subset' using the original particles as "full set of items" and the refined downsampled particles as "other set" to do an intersection. Then I did 'scipion -  assign alignment' to have the refined angles on the original particles from the subset. But I will try, as you say, to reextract them without applying shifts and assign the alignments.

**Comment by azazellochg** [comment]
Hi @gilcantero ,
> I assign the angles from the classification to the non-downsampled particles and run an auto-refine or a new 3D classification (using relion 3), and in both cases the models are worse than the original. 

Auto-refine or cl3d will always start from random angles, unless you are doing local searches. It might not work if you start from non-downsampled data.

**Comment by azazellochg** [comment]
@delarosatrevin  can we close this? there will be a new options (https://github.com/scipion-em/scipion-em/pull/70) to simplify these cases

**Comment by pconesa** [comment]
Hi, alignment assing, will apply only the decimal part of the shifts, if user activates the option (advance).
Additionally, we have modified the "apply shifts" in extract coordinates to be also "advance".

**Comment by pconesa** [comment]
Just to be clear; If you extract coordinates applying shifts, only the integer part fo the shifts are taken into account to avoid interpolation. So there will be a mismatch by the decimal part, that will try to compensate the alignment assign in Scipion 3.
