### ISSUE TITLE
Work in Relion 3.1 picking

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-relion#117]
- [x] Add new param LoG upper thresold
- [x] Check other parameters (both 3.0 and 3.1)
- [ ] Check the insane amount of coordiantes given by LoG test in 3.1 (fine in 3.0)

**Comment by azazellochg** [comment]
I didnt find log picker test

**Comment by delarosatrevin** [comment]
I was using this test (a bit of a mixed workflow, but mainly relion):
scipion tests relion.tests.test_workflow_relion3.TestWorkflowRelion3Betagal

Now I'm getting a reasonable number of particles out of LoG picker. So, I'm closing this issue. 
We can reopen if we have the problem again.
