### ISSUE TITLE
movie alignment dose error

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-relion#118]
Dear Sciponers,

I've tried to align a movie with relion motioncor. But I get next error, because the dose was not defined in the import protocol. The error always happens, even if the dose weighted is disable. In pyworkflow/em/protocol/protocol_align_movies.py, where the error comes considers that the movie has a dose parameter

Kind regards

Vilas

  STARTED: processMovieStep, step 2
00022:     2019-12-06 16:18:37.808702
00023:   Processing movie: Runs/001885_ProtRelionMotioncor/tmp/movie_000001/Jul30_12.49.06.tif
00024:   Traceback (most recent call last):
00025:     File "/home/vilas/software/scipion/pyworkflow/protocol/protocol.py", line 186, in run
00026:       self._run()
00027:     File "/home/vilas/software/scipion/pyworkflow/protocol/protocol.py", line 237, in _run
00028:       resultFiles = self._runFunc()
00029:     File "/home/vilas/software/scipion/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00030:       return self._func(*self._args)
00031:     File "/home/vilas/software/scipion/pyworkflow/em/protocol/protocol_movies.py", line 375, in processMovieStep
00032:       self._processMovie(movie)
00033:     File "/home/vilas/software/scipion/software/lib/python2.7/site-packages/relion/protocols/protocol_motioncor.py", line 201, in _processMovie
00034:       preExp, dose = self._getCorrectedDose(self.inputMovies.get())
00035:     File "/home/vilas/software/scipion/pyworkflow/em/protocol/protocol_align_movies.py", line 489, in _getCorrectedDose
00036:       preExp += dose * (firstFrame - 1)
00037:   TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
00038:   Protocol failed: unsupported operand type(s) for *: 'NoneType' and 'int'

**Comment by azazellochg** [comment]
Thank you  @Vilax , fixed in 89548f178b4c747edb6f173781a80673a1a17f35
