### ISSUE TITLE
Gentle clean/harsh clean in reliom

### ISSUE THREAD

**Issue by andreanans** [scipion-em/scipion-em-relion#136]
Hi,

Any chance that we will get the harsh and gentle clean options for Relion jobs?

Thank you

Andrea

**Comment by delarosatrevin** [comment]
Hi @andreanans , thanks again for your feedback. I will try to add this feature after the Relion3.1 support is complete.

**Comment by azazellochg** [comment]
I'll make a script to do gentle clean of relion jobs. According to relion 3.1 code:
1) find all finished relion protocols
2) do not clean imports, mask create, resmap, select, join, manualpick, subtract
3) recursively find all subdirs
4) for motioncor remove *.log, com, out, err
5) for ctf remove gctf*.out, gctf*.err, entire Micrographs folder
6) for autopick remove *spi FOM maps
7) for extract remove individual *_extract.star
8) for cls2d/3d, ref3d, init, mbody remove all iter except the last one
9) for ctf ref remove:
*_wAcc_optics-group*.mrc";
*_xyAcc_optics-group*.mrc";
*_aberr-Axx_optics-group_*.mrc";
*_aberr-Axx_optics-group_*.mrc";
*_aberr-Axy_optics-group_*.mrc";
*_aberr-Ayy_optics-group_*.mrc";
*_aberr-bx_optics-group_*.mrc";
*_aberr-by_optics-group_*.mrc";
*_mag_optics-group_*.mrc";
*_fit.star";
*_fit.eps";
10) for polishing remove:
*_FCC_cc.mrc";
*_FCC_w0.mrc";
*_FCC_w1.mrc";

11) for postprocess remove *masked.mrc
12) move all files found to trash, keeping dir structure
