### ISSUE TITLE
'relion - reconstruct halfmaps' protocol

### ISSUE THREAD

**Issue by JuhaHuiskonen** [scipion-em/scipion-em-relion#137]
When alignment is assigned to a different set of particles (for example on the original particle stack after focused classification using partial signal subtraction) there is no easy way to calculate the two half maps for post processing. 

Could you please consider implementing 'relion - reconstruct halfmaps' protocol, which would take into account the original assignment to the two subsets (half 1 and half 2), reconstruct the two half maps to Nyqyist using relion_reconstruct, and create an output accepted by 'relion - post-processing' protocol (previous refinement protocol).

The only alternative is to take the particles, using 'scipion - subset' to split it in two sets.  This does not honour the original subsets. Also if two separate maps are calculated, they cannot be used for 'relion - post-processing'.

**Comment by azazellochg** [comment]
Half-addressed in #335

**Comment by azazellochg** [comment]
Relion - reconstruct protocol can be executed twice to produce two halves, which can then be input to post-process. rlnRandomSubset is preserved when running subtract protocol.
