### ISSUE TITLE
relion particle extraction fails in python3

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-relion#138]
**Describe the bug**
relion particle extract is failing. I'm getting this:
00010:   Traceback (most recent call last):
00011:     File "/home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 181, in run
00012:       self._run()
00013:     File "/home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 1303, in _run
00014:       self._insertAllSteps()  # Define steps for execute later
00015:     File "/home/pablo/desarrollo/scipion-em/pwem/protocols/protocol_particles.py", line 168, in _insertAllSteps
00016:       micDict = self._loadInputList()
00017:     File "/home/pablo/desarrollo/scipion-em/pwem/protocols/protocol_particles.py", line 389, in _loadInputList
00018:       micDict = self._loadInputCoords(micDict)
00019:     File "/home/pablo/desarrollo/scipion-em/pwem/protocols/protocol_particles.py", line 422, in _loadInputCoords
00020:       for micKey, mic in micDict.items():
00021:   RuntimeError: OrderedDict mutated during iteration

**To Reproduce**
use relion particle extraction

**Desktop (please complete the following information):**
 - Scipion version: [3.0]
 - Relion plugin version: branch python3_migration

**Comment by pconesa** [comment]
ok, xmipp extraction fails too. MIght be a common problem. I'll have a look.

**Comment by azazellochg** [comment]
Relion 31 + scipion 3 is now in pre-pre-pre-alpha, so most of protocols won't work at all.

**Comment by azazellochg** [comment]
@pconesa I have just checked with/without streaming and it works

**Comment by pconesa** [comment]
Leave it closed, it happens when some mics are not picked or ctfs are a subset. I have the fix and is in the parent class, will hapen for relion and xmipp.
