### ISSUE TITLE
motion corr fails with 

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-relion#140]
On behalf of one of our users: 

**Describe the bug**
Some movies were aligned 14, I guess and then an error happened:
Exception: 'data_local_motion_model' block was not found

**Desktop (please complete the following information):**
 - Scipion version: 2.0
 - Relion plugin version : She is updated

**Additional context**

She also said that she was continuing several times getting more movies aligned, until this stop working anymore.

Las part of the log file is :

00659:   STARTED: processMovieStep, step 15
00660:     2020-02-24 14:52:27.033518
00661:   Processing movie: Runs/000388_ProtRelionMotioncor/tmp/movie_000014/FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions.mrc
00662:   mpirun -np 10 --map-by node  `which relion_run_motioncorr_mpi` --i FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions_input.star --o output/ --use_own --first_frame_sum 1 --last_frame_sum 19 --bin_factor 1.000000 --bfactor 150 --angpix 1.100000 --patch_x 5 --patch_y 5 --j 28 --dose_weighting --dose_per_frame 1.700000 --preexposure 0.000000 --voltage 300  
00663:   /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi: /services/tools/scipion/2.0.0/software/lib/libtiff.so.5: no version information available (required by /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi)
00664:   /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi: /services/tools/scipion/2.0.0/software/lib/libtiff.so.5: no version information available (required by /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi)
00665:   /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi: /services/tools/scipion/2.0.0/software/lib/libtiff.so.5: no version information available (required by /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi)
00666:   /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi: /services/tools/scipion/2.0.0/software/lib/libtiff.so.5: no version information available (required by /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi)
00667:   /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi: /services/tools/scipion/2.0.0/software/lib/libtiff.so.5: no version information available (required by /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi)
00668:   /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi: /services/tools/scipion/2.0.0/software/lib/libtiff.so.5: no version information available (required by /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi)
00669:   /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi: /services/tools/scipion/2.0.0/software/lib/libtiff.so.5: no version information available (required by /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi)
00670:   /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi: /services/tools/scipion/2.0.0/software/lib/libtiff.so.5: no version information available (required by /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi)
00671:   /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi: /services/tools/scipion/2.0.0/software/lib/libtiff.so.5: no version information available (required by /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi)
00672:   /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi: /services/tools/scipion/2.0.0/software/lib/libtiff.so.5: no version information available (required by /services/tools/scipion/2.0.0/software/em/relion-3.0/bin/relion_run_motioncorr_mpi)
00673:    === RELION MPI setup ===
00674:    + Number of MPI processes             = 10
00675:    + Master  (0) runs on host            = risoe-r07-g003
00676:    + Slave     1 runs on host            = risoe-r07-g003
00677:    + Slave     2 runs on host            = risoe-r07-g003
00678:    + Slave     3 runs on host            = risoe-r07-g003
00679:    + Slave     4 runs on host            = risoe-r07-g003
00680:    + Slave     5 runs on host            = risoe-r07-g003
00681:    + Slave     6 runs on host            = risoe-r07-g003
00682:    + Slave     7 runs on host            = risoe-r07-g003
00683:    + Slave     8 runs on host            = risoe-r07-g003
00684:    + Slave     9 runs on host            = risoe-r07-g003
00685:    =================
00686:   FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions.mrc
00687:   FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions.mrc
00688:   FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions.mrc
00689:   FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions.mrc
00690:   FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions.mrc
00691:   FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions.mrc
00692:   FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions.mrc
00693:   FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions.mrc
00694:   FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions.mrc
00695:   FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions.mrc
00696:    Using our own implementation based on MOTIONCOR2 algorithm
00697:    to correct beam-induced motion for the following micrographs: 
00698:     * FoilHole_18276557_Data_18277147_18277148_20190719_1431_Fractions.mrc
00699:    Correcting beam-induced motions using our own implementation ...
00700:     24/  24 sec ............................................................~~(,_,">
00701:    Generating logfile.pdf ... 
00702:   000/??? sec ~~(,_,">                                                          [oo]gs: /services/tools/scipion/2.0.0/software/lib/libtiff.so.5: no version information available (required by /lib64/libgs.so.9)
00703:      0/   0 sec ............................................................~~(,_,">
00704:    Done! Written: output/logfile.pdf and output/corrected_micrographs.star
00705:   Erasing.....movieFolder: Runs/000388_ProtRelionMotioncor/tmp/movie_000014
00706:   FINISHED: processMovieStep, step 15
00707:     2020-02-24 14:52:54.767883
00708:   Traceback (most recent call last):
00709:     File "/services/tools/scipion/2.0.0/pyworkflow/protocol/protocol.py", line 186, in run
00710:       self._run()
00711:     File "/services/tools/scipion/2.0.0/pyworkflow/protocol/protocol.py", line 1289, in _run
00712:       self._runSteps(startIndex)
00713:     File "/services/tools/scipion/2.0.0/pyworkflow/protocol/protocol.py", line 1161, in _runSteps
00714:       self._stepsCheckSecs)
00715:     File "/services/tools/scipion/2.0.0/pyworkflow/protocol/executor.py", line 133, in runSteps
00716:       stepsCheckCallback()
00717:     File "/services/tools/scipion/2.0.0/pyworkflow/em/protocol/protocol_movies.py", line 245, in _stepsCheck
00718:       self._checkNewOutput()
00719:     File "/services/tools/scipion/2.0.0/pyworkflow/em/protocol/protocol_align_movies.py", line 198, in _checkNewOutput
00720:       newMovie = self._createOutputMovie(movie)
00721:     File "/services/tools/scipion/2.0.0/software/lib/python2.7/site-packages/relion/protocols/protocol_motioncor.py", line 415, in _createOutputMovie
00722:       tableName='local_motion_model')
00723:     File "/services/tools/scipion/2.0.0/software/lib/python2.7/site-packages/relion/convert/metadata.py", line 58, in __init__
00724:       self.read(fileName, tableName)
00725:     File "/services/tools/scipion/2.0.0/software/lib/python2.7/site-packages/relion/convert/metadata.py", line 110, in read
00726:       self.readStar(f, tableName)
00727:     File "/services/tools/scipion/2.0.0/software/lib/python2.7/site-packages/relion/convert/metadata.py", line 84, in readStar
00728:       self._findDataLine(inputFile, dataStr)
00729:     File "/services/tools/scipion/2.0.0/software/lib/python2.7/site-packages/relion/convert/metadata.py", line 230, in _findDataLine
00730:       raise Exception("'%s' block was not found" % dataStr)
00731:   Exception: 'data_local_motion_model' block was not found
00732:   ------------------- PROTOCOL FAILED (DONE 15/3905)

**Comment by delarosatrevin** [comment]
Thanks for reporting this @pconesa ! I have already encountered this issue and even better, I have the fix. I will try to put in in the next plugin release (not for Scipion 3)

**Comment by pconesa** [comment]
Cool! I've asked Mar (user) to register and provide more data if needed!

**Comment by delarosatrevin** [comment]
I think it is not needed for now. Thanks anyway.

**Comment by pconesa** [comment]
MAy be she can install a branch an test it...I can guide her but will need the branch

**Comment by marperezruiz** [comment]
Many thank @pconesa and @delarosatrevin for your response. It would be super if we can use the new branch (when it will be possible). Thanks ;)

**Comment by delarosatrevin** [comment]
I will let you know when it is ready.

**Comment by azazellochg** [comment]
@pconesa @marperezruiz sorry for taking so long, the error is fixed in the latest plugin release.

**Comment by pconesa** [comment]
Thank you @azazellochg , I can see there is a release for production scipion.
@marperezruiz , you can get it by typying:

 `scipion installp -p scipion-em-relion`

Check 1.0.9 version is installed and current uninstalled:

````
Installing collected packages: scipion-em-relion
  Found existing installation: scipion-em-relion 1.0.8
    Uninstalling scipion-em-relion-1.0.8:
      Successfully uninstalled scipion-em-relion-1.0.8
Successfully installed scipion-em-relion-1.0.9
````

**Comment by marperezruiz** [comment]
Thank you very much @azazellochg @delarosatrevin @pconesa !!
