### ISSUE TITLE
assign optics doesnt support streaming

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#188]

**Comment by delarosatrevin** [comment]
I will work on this as soon as I finish the OpticsGroup re-factoring. This issue is very important since it is blocking right now the streaming if one wants to use Relion Motioncorr.

**Comment by delarosatrevin** [comment]
Finally, we have agreed that this protocol does not need to work in streaming. The idea is that during streaming, a single, default optics group will be created and later in the processing, the real optics groups should be assigned.
