### ISSUE TITLE
extract particles creates empty stacks

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#189]
3.1
no streaming, batch size 0 (all). Running `04378:   mpiexec -mca orte_forward_job_control 1 --oversubscribe -n 48  `which relion_preprocess_mpi`  --i micrographs_00001-01532.star --part_star micrographs_00001-01532_particles.star  --coord_dir "." --coord_suffix .coords.star --part_dir "." --extract  --extract_size 128 --bg_radius 27 --invert_contrast --norm --scale 64`

What happens is that extraction works perfectly in tmp folder, but at the end it create empty mic_XXXXXX.mrcs in extra folder

**Comment by azazellochg** [comment]
![image](https://user-images.githubusercontent.com/6952870/85742918-8b663800-b6fb-11ea-91a5-ea62cb83554c.png)

**Comment by azazellochg** [comment]
couldn't reproduce with tutorial dataset, will need to look more.

**Comment by azazellochg** [comment]
reproduced when submitting jobs to the queue, needs further investigation..

**Comment by delarosatrevin** [comment]
Will be addressed in a more general issue
