### ISSUE TITLE
too many columns rendered by default?

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#19]
relion3 branch
I open set of particles after 2d CLS, and the default table looks a bit of overkill, also making it slow to render:
![screenshot_20190115_163011](https://user-images.githubusercontent.com/6952870/51194422-ef6bb680-18e2-11e9-9b59-da3217e086f2.png)

I am thinking maybe we should not display the following columns by default:

- label
- comment
- coordinate.micId (micid is enough?)
- ctfmodel.micobj.index
- ctfmodel.micobj.filename (this causes very slow rendering)
- ctfmodel.micobj.index
- ctfmodel.micobj.micname (same as coordinate.micname in most cases)
- ctfmodel.micobj.plotglobal.index
- ctfmodel.micobj.plotglobal.samplingrate
- ctfmodel.micobj.psdjpeg.index
- ctfmodel.micobj.psdjpeg.filename (this causes very slow rendering, it's same thing 
 as ctfmodel.micobj.filename)
- ctfmodel.micobj.psdjpeg.samplingrate
- ctfmodel.micobj.thumbnail.index
- ctfmodel.micobj.thumbnail.filename
- ctfmodel.micobj.thumbnail.samplingrate

**Comment by delarosatrevin** [comment]
@azazellochg Do you mean after Relion - 2D classification? The output is SetOfClasses2D...if you create a subset of particles...and visualize it, I still do not get so many columns...can you specify better this case?

**Comment by azazellochg** [comment]
@delarosatrevin I already forgot what I did there.. hehe ^) I think, I opened result viewer and displayed particles from a certain class. The problem is not relion-specific I assume, since relion only adds a few extra columns with its own metadata. The thing is that ctfmodel.micobj.* duplicates a whole bunch of micobj.* things. This issue should go to scipion core.

**Comment by azazellochg** [comment]
Transferred to xmippViz repo
