### ISSUE TITLE
Multibody refinement not working...

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-relion#191]
It probably is worth doing this en scipion3 but just in case. We were getting this error:

Is a validation error.

https://github.com/scipion-em/scipion-em-relion/blob/devel/relion/protocols/protocol_multibody.py#L264

For some reason (probably saving time) we comment multi-body refinement test in buildbot. We are going to rescue it and see if it works.

Should it be working?
![multibody](https://user-images.githubusercontent.com/785633/86020113-c6cc7380-ba27-11ea-99d6-fee358f3e54a.jpeg)

**Comment by azazellochg** [comment]
Why / how are you using scipion 2 with devel plugin branch?

**Comment by pconesa** [comment]
Nope, this is not devel branch is released code: Scipion2 + scipion-em-relion at pypi for Scipion2.

**Comment by pconesa** [comment]
I guess the right link is this one: https://github.com/scipion-em/scipion-em-relion/blob/support/relion/protocols/protocol_multibody.py#L273

**Comment by azazellochg** [comment]
Tests files are not for 3.1, so the buildbot test will fail. Scipion 3 + relion 3.1 the protocol starts but I have not waited for it to finish. I won't be fixing scipion 2 anymore, so any volunteering is welcome.

**Comment by pconesa** [comment]
We are testing relion multibody refinement.....
Scipion3 - relion 3.0.0b1.

We are getting: 
ERROR: not all necessary variables defined in _optics.star file: rlnPixelSize, rlnVoltage and rlnSphericalAberration. Make sure to convert older STAR files anew in version-3.1, with relion_convert_star.

The refinement protocol was a 3.0 one.

Is this not compatible?

**Comment by azazellochg** [comment]
The error says you are using relion 3.1
To go to 3.1 you need to either convert and reimport particles or try
assign optics protocol and then try multibody.

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by delarosatrevin** [comment]
Grigory, I think that we are converting the particles and we should
generate a proper optics table. With the latest changes, there is no need
for assign-optics protocol.

**Comment by pconesa** [comment]
I'm confused. 

Should it work with particles from relion3.0?

If not.....can it be validated to get intructions , otherwise this is going to be a frequent issue?

**Comment by azazellochg** [comment]
ok, there are few issues here:

1) an original error in support branch for scipion2.0/relion30 (I don't think @delarosatrevin and me can support this any longer)
2) scipion3.0 error when going from 3d ref in relion30 to mb in relion31 (we have to check this)
3) scipion3.0 mb protocol for relion 3.1 (it's working as you recently confirmed on slack)
4) test for mb and relion31 (test files need updating if you plan to run it in the buildbot @pconesa )

**Comment by pconesa** [comment]
Thanks!

I think 1 can be discarded

2 I guess is useful for users with data in relion30 that con to continue in relion 3.1 but you know the details and if is worth supporting it or not. If not I'd, at least , inform users about it if possible to detect a relion30 refine as input of relion3.1 mb.

3 great, seems to work!

4. Is up to you if you want build it to test it. Now is excluded due to lack of 2 GPUs, but we will probably get an update of the worker with 2 GPUs.

**Comment by delarosatrevin** [comment]
What is the status of this issue?
@pconesa could you try this again?

**Comment by azazellochg** [comment]
@delarosatrevin we need to check (2)
