### ISSUE TITLE
ctf refine viewer

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#194]
need to check options depending on protocol params, also output beam tilt fns are wrong.

**Comment by delarosatrevin** [comment]
@azazellochg Can you describe better this issue? I can try to take a look and fix it.

**Comment by azazellochg** [comment]
@delarosatrevin the viewer shows defocus button even if protocol was not used to refine defocus. Also 2 beamtilt output images have changed their names

**Comment by azazellochg** [comment]
For mag dist correction we need to display:
![image](https://user-images.githubusercontent.com/6952870/87879755-889df080-c9e4-11ea-8852-10fdfc392377.png)

- mag_disp_x_fit_optics-group_1.mrc
- mag_disp_x_optics-group_1.mrc
- mag_disp_y_fit_optics-group_1.mrc
- mag_disp_y_optics-group_1.mrc

For beamtilt we need to display:

- aberr_delta-phase_iter-fit_optics-group_1_N-4.mrc
- aberr_delta-phase_lin-fit_optics-group_1_N-4.mrc
- aberr_delta-phase_lin-fit_optics-group_1_N-4_residual.mrc
- aberr_delta-phase_per-pixel_optics-group_1.mrc
- beamtilt_delta-phase_iter-fit_optics-group_1_N-3.mrc
- beamtilt_delta-phase_lin-fit_optics-group_1_N-3.mrc
- beamtilt_delta-phase_lin-fit_optics-group_1_N-3_residual.mrc
- beamtilt_delta-phase_per-pixel_optics-group_1.mrc
