### ISSUE TITLE
assign optics issues

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#196]
More things to address:

- [x] assignment doesnt work. To reproduce: assign optics from gui or star file to a set of imported movies. Launch motioncorr  -> after convertinput optics table has default values instead of assigned ones. Basically, opticsgroupinfo is empty for output movies from assign protocol.
- [x] do we force users to have data_micrographs table in the input star? So, they cant have data_movies or data_particles. And they have to have rlnMicrographName column. We should add a validation for this then.
- [x] protocol prints only the last og params when og>1
- [x] mtf column from star file is still assigned if mtf file doesnt exist
- [x] check if defects file exists

**Comment by delarosatrevin** [comment]
@azazellochg Could you please take a look to check which of these points remains?
