### ISSUE TITLE
Subtract projection protocol not working

### ISSUE THREAD

**Issue by cossorzano** [scipion-em/scipion-em-relion#209]
When calling subtract projection, the protocol complains

00013:   STARTED: convertInputStep, step 1, time 2020-08-05 23:04:49.436859
00014:   Traceback (most recent call last):
00015:     File "/home/coss/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 188, in run
00016:       self._run()
00017:     File "/home/coss/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 239, in _run
00018:       resultFiles = self._runFunc()
00019:     File "/home/coss/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 235, in _runFunc
00020:       return self._func(*self._args)
00021:     File "/home/coss/scipion3/scipion-em-relion/relion/protocols/_legacy/protocol30_subtract.py", line 139, in convertInputStep
00022:       imgSet, self._getFileName('input_star'), self._getExtraPath())
00023:   TypeError: writeSetOfParticles() takes 2 positional arguments but 3 were given
00024:   Protocol failed: writeSetOfParticles() takes 2 positional arguments but 3 were given
00025:   FAILED: convertInputStep, step 1, time 2020-08-05 23:04:49.439553

**Comment by azazellochg** [comment]
Hi @cossorzano, we have decided that we will not provide support and bugfixes to relion 3.0 anymore. So this won't be fixed.
