### ISSUE TITLE
motioncorr

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#210]
Hi @pconesa, @azazellochg  and @delarosatrevin 

  I am writing in relation to motioncorr2. As you may know we have a protocol (report-html) that makes available a summary of the image processing using a web server. This protocol uses different images computed by mationcorr2 that are not available (at least with the same name) in motioncorr2 run through relion. 

 The images needed are:

 1) a thumbnail of the microscgraph
 2) PSD
 3) Plot with frames shift

I was thinking in normalizing the output of these two flavors of motioncorr2 so the created objects and files are as similar as possible and report-html may use both protocols.
Is these OK with you? Do you foresee any special difficultty?

  cheers

   @rmarabini

**Comment by azazellochg** [comment]
Hi @rmarabini ,

I'm not interested in adding xmipp back to relion plugin as we are trying to get rid of it as much as possible. Using xmipp (there is nothing else at the moment) to calculate 1 and 2 makes any mc protocol much slower.
Both mc2 and relion mc make now shift per frame global plot for all movies which I find more useful. Relion mc protocol does not calculate any of 1/2/3 images.

**Comment by delarosatrevin** [comment]
@rmarabini Thanks for your feedback. I think that maybe you could add this functionality to the report HTML protocol.  In that. way you can have this information without the need to force each MC protocol to implement it.

**Comment by rmarabini** [comment]
Hi @delarosatrevin, @azazellochg and @pconesa,

  So far there are three protocols able to align movies in scipion  (motioncorr, relion-motion-correction and xmipp-correlation) The three of them are able to create PSDs and shift plots which are the information I need to report but these data is not stored as a scipion object so I do not have access to them from another protocol. I think a possible way to solve this problem would be to add two optional attributes to the output setOfMicrographs  one with the name of the PSD file and another with the name of the plot file  (if available). (We may call them psd  and plotshifts respectively.)

  Do you think this is the way to go?

  cheers

    Roberto

**Comment by delarosatrevin** [comment]
Will be addressed in a more general issue
