### ISSUE TITLE
CTF manual grouping is not working in Relion

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-relion#213]
**Describe the bug**
CTF manual grouping is not working in Relion, it is using xmipp Metadata class and overwriting the optics table.

**Comment by azazellochg** [comment]
part of https://github.com/scipion-em/scipion-em-relion/issues/195

**Comment by delarosatrevin** [comment]
Fixed 4ae313a575a22eae2cd10e12b7954a79227fac4b
