### ISSUE TITLE
Relion - Extract Particles fail

### ISSUE THREAD

**Issue by fonsecareyna82** [scipion-em/scipion-em-relion#219]
**Describe the bug**
Got unexpected field names: ['rlnImagePixelSize']

**Screenshots**
![Captura de pantalla de 2020-09-09 17-04-25](https://user-images.githubusercontent.com/34970661/92616839-fe288d80-f2be-11ea-9e1b-43427cc0fccd.png)

**Comment by azazellochg** [comment]
Thanks @fonsecareyna82 , which version of plugin is this?

**Comment by azazellochg** [comment]
Also, is this streaming?

**Comment by fonsecareyna82** [comment]
I just ran the test. I have the devel branch installed in developer mode. You can see the error also in buildbot. It's the only relion test that fails. 
http://scipion-test.cnb.csic.es:9980/#/builders/54/builds/393

**Comment by azazellochg** [comment]
@delarosatrevin the problem is that updateAll tries to update non-existing rlnImagePixelSize, but there is rlnMicrographPixelSize. 
```
og.updateAll(rlnImagePixelSize=self._getNewSampling(),
                         rlnImageSize=self.getNewImgSize())
```
