### ISSUE TITLE
3D Classification visualization

### ISSUE THREAD

**Issue by gilcantero** [scipion-em/scipion-em-relion#221]
Good morning,
I run a relion 3D classification after expanding particles (13M of particles), with a box size of 200px, 12 clases and without aligning.  When it finished I clicked on analyzed results, then in the eye to visualize in chimera and no problem, but when I do the same for view the clases with its number of particles,etc, to save those I want to work with, the eye becomes red when pressed, return to grey qhen I stop clicking and nothing it is showed. After 30 mins aprox an error message is shown in the terminal, which is the following:

/home/virus> Exception in thread "main" java.lang.OutOfMemoryError:
Java heap space
        at java.lang.String.toUpperCase(String.java:2810)
        at java.lang.String.toUpperCase(String.java:2833)
        at org.sqlite.RS.findColumn(RS.java:163)
        at org.sqlite.RS.getString(RS.java:569)
        at
xmipp.viewer.scipion.ScipionMetaData.loadValues(ScipionMetaData.java:213)
        at
xmipp.viewer.scipion.ScipionMetaData.loadData(ScipionMetaData.java:151)
        at
xmipp.viewer.scipion.ScipionMetaData.<init>(ScipionMetaData.java:91)
        at
xmipp.viewer.scipion.ScipionMetaData.<init>(ScipionMetaData.java:68)
        at
xmipp.viewer.windows.ImagesWindowFactory.openScipionMetadata(ImagesWindowFactory.java:223)
        at xmipp.viewer.scipion.ScipionViewer.openFile(ScipionViewer.java:71)
        at xmipp.viewer.scipion.ScipionViewer.main(ScipionViewer.java:52)

**Desktop (please complete the following information):**
 - Scipion version: 2.0
 - Relion plugin version: 1.0.9
 - Relion binary version: 3.0

Thank you very much,
David.

**Comment by azazellochg** [comment]
Hi @gilcantero , you could try to increase java memory setting

JAVA_MAX_MEMORY = 4

in your <scipion home>/config/scipion.conf where 4 is in Gb of RAM, though not sure if so many particles will open..

**Comment by gilcantero** [comment]
Hi @azazellochg, I have changed JAVA_MAX_MEMORY to 4 as you said and it was still too low. I have changed to 20 and now it opens, so thank you very much!

David.

**Comment by azazellochg** [comment]
Great!
The Scipion performance with big datasets is a known issue, which we hopefully will start working on soon.
