### ISSUE TITLE
relion-subtract

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#225]
Hi @azazellochg,

    I have installed scipion-em-relion with relion 3.1. When I try to execute the protocol relion_subtract I see that it does not longer use the program relion_project but it uses relion_subtract_particle. 

  relion_subtract_particle uses as input a relion optimizer file, in the current implementation this file is not generated  on the fly but copied from a previous relion 3D execution.  That is relion_substract can no longer use any set of volume/particles as input but only those created by relation in the same project. 

Since I would like to use  relion_subtract with no relion generated data the question is:  Can the protocol be modified so a "relion optimizer file is created on the fly" or, at least, can we add the an alternative option to relion_subtract that uses relion_project and therefore, can use as input a volume and a set of particles?

   thanks

   roberto

**Comment by azazellochg** [comment]
Hi @rmarabini , I'm afraid with current number of protocols I won't have time to implement something non-standard here. You could add an option to the current protocol and I'll be happy to review it.

**Comment by pconesa** [comment]
@azazellochg , how is this related to the logging centralization? I don't see it.

**Comment by azazellochg** [comment]
It's not. Difficult Monday morning 😅

**Comment by gilcantero** [comment]
Hi @rmarabini, I am having a similar issue, did you find a solution to subtract using relion with a refinement which is not from relion?

**Comment by rmarabini** [comment]
> Hi @rmarabini, I am having a similar issue, did you find a solution to subtract using relion with a refinement which is not from relion?
Hi @gilcantero, 

I have modified the project protocol in order to allow projection subtraction from data which is not from relion. This modification is in one of my branches and it has NOT been properly  tested. If you want I may share the branch which but use it at your own risk

**Comment by gilcantero** [comment]
If installed separately from scipion3, is there any risk of breaking my project? If the only problem I might face is the protocol not working but not breaking anything It might be useful.

Thank you.

**Comment by rmarabini** [comment]
Hi,

    The protocol will not break your project but I do not think it is
working as it should. I will let you know
when I am happy with it.

   Roberto

**Comment by gilcantero** [comment]
Ok, thank you Roberto

**Comment by rmarabini** [comment]
Hi @JuhaHuiskonen  and @gilcantero you are welcome to use the "projection subtraction" new implementation available in branch rm_subtraction. As far as I know it works (I tested it with JuhaHuiskonen data) but use it at your own risk. Note that this is not (yet) an official release therefore you do not have access to it using  scipion plugin manager. You need to download it  using git and install it manually.
