### ISSUE TITLE
relion_autopicking wizard

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#23]
Not the Log picker!
After running once in optimizae mode and clicking in the wizard I get this:
`Labels MDL_MICROGRAPH or MDL_IMAGE not found in metadata Tmp/4290.outputMicrographsSubset/micrographs.xmd`
@delarosatrevin is it because of pending xmipp PRs?

**Comment by delarosatrevin** [comment]
Is this still happening?

**Comment by azazellochg** [comment]
I'm pulling latest xmipp now, will check again

**Comment by delarosatrevin** [comment]
Don't worry, I think I know where the issue is and it is not solved with
latest version of Xmipp.

**Comment by delarosatrevin** [comment]
Fixed in ca39a5b91af1a22b
