### ISSUE TITLE
Relion optics group image size is not correctly updated by protocols

### ISSUE THREAD

**Issue by JuhaHuiskonen** [scipion-em/scipion-em-relion#230]
This is related to issue scipion-em/scipion-em#161.  

_rlnImageSize in the STAR file under data_optics gets always its original value (e.g. from particle picking).  It seems that at least the following protocols fail to update this value: 'relion - particles extraction' and 'localrec - extract subparticles'.  

So currently I think any Relion workflow that changes the box size will fail. 

Scipion v 3.0.5

**Comment by JuhaHuiskonen** [comment]
Thanks Pablo.  Yes, it is likely a bug in the Relion plugin in the part where the Relion STAR file is generated.   The new particle box size (if it has been changed) is not written correctly to the optics group section in the STAR file (the original box size is used instead of the current one).

**Comment by azazellochg** [comment]
Hi @JuhaHuiskonen , I've just updated devel branch from rc3.0.0b4. I did multiple extract coordinates and then extracting particles with different size (binning) and ImageSize is correct in the optics table. Can you update and check?

**Comment by JuhaHuiskonen** [comment]
Funnily enough if I run the extraction again with the new version, then the particle size is written correctly to the optics table.  So it seems this has been fixed.
