### ISSUE TITLE
bugs found executing relion devel

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#236]
1) relion_reconstruct:  It is not possible to give as input phase flipped images. Before the protocol checked  if  imgSet.isPhaseFlipped()==true and added the flag " --ctf_intact_first_peak" automatically. Follows a "git diff" between devel and the proposed code.
```
             params += ' --ctf'
             if self.ctfIntactFirstPeak:
                 params += ' --ctf_intact_first_peak'
+
+            if imgSet.isPhaseFlipped():
+                params += ' --ctf_phase_flipped'

```

2) Protocol protocol_classify3d.py, viewer that display the Pmax is wrong (see attached image)
Y axis should go form 0 to 1, the present use goes from 1 then to 0.3 then up.  The shape of the curve is wrong. The function should look like a logarithm asymptotic to one .

![error_Pmax](https://user-images.githubusercontent.com/10512802/97172966-1fbad700-1790-11eb-8d3a-ca948861d0c2.png)

**Comment by azazellochg** [comment]
Thank you @rmarabini ! Fixed.
