### ISSUE TITLE
auto refine 3d missing params

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#24]
Optimization tab is totally empty...
![screenshot_20190115_193138](https://user-images.githubusercontent.com/6952870/51204802-58abf380-18fc-11e9-8945-8767b7f1d9a8.png)

**Comment by delarosatrevin** [comment]
Well, with the current organization of the parameters, the Optimisation tab is only needed in CLASSIFY mode. 

Fixed in af4ec15cf5c42cc0
