### ISSUE TITLE
Bayesian polishing error

### ISSUE THREAD

**Issue by JuhaHuiskonen** [scipion-em/scipion-em-relion#240]
Relion particle  polishing fails with error

"There is no movie metadata STAR file for any micrographs!"

Here the inputs are the aligned movies generated with 'relion - motion correction'

Scipion v. 3.0.5

**Comment by delarosatrevin** [comment]
Relion plugin branch/version? I fixed some time ago a bug that produced the same error message.

**Comment by JuhaHuiskonen** [comment]
Relion plugin 3.0.0, branch devel.

**Comment by azazellochg** [comment]
Hi @JuhaHuiskonen , does it still happen? Can you send me movies.sqlite (output from relion motion correction) and particles.sqlite (input for polishing)?

**Comment by JuhaHuiskonen** [comment]
This is working now, thanks!
