### ISSUE TITLE
grouping of frames in motion correction 

### ISSUE THREAD

**Issue by JuhaHuiskonen** [scipion-em/scipion-em-relion#249]
I have 'group frames' option set to 3 frames.  It seems however that this is not taken into account in the motioncorr run.  The command line the protocol produces is this:

relion_run_motioncorr --i micrograph001_input.star --o output/ --use_own --first_frame_sum 1 --last_frame_sum 22 --bin_factor 2.000000 --bfactor 150 --angpix 0.67500 --patch_x 1 --patch_y 1 --j 4 --dose_weighting --dose_per_frame 0.720000 --preexposure 0.000000

**Comment by azazellochg** [comment]
Thank you, @JuhaHuiskonen ! Fixed in devel.
