### ISSUE TITLE
issue with micrograph thumbnails in motion correction

### ISSUE THREAD

**Issue by JuhaHuiskonen** [scipion-em/scipion-em-relion#250]
If I create thumbnails in motion correction (right), the subsequent ctffind4 run fails with the error: "no such table: Properties". 

<img width="475" alt="Screenshot 2020-11-08 at 12 10 54" src="https://user-images.githubusercontent.com/20352352/98462265-affb1200-21bb-11eb-9eaf-75d38e871a76.png">

Otherwise an identical run (left) that does not create thumbnails is fine.

**Comment by azazellochg** [comment]
Hm, can't reproduce this. Do you have eman2 installed? Making thumbnails requires e2proc2d. Does motioncor work properly?

**Comment by JuhaHuiskonen** [comment]
That explains it, we don't have eman2 installed. Maybe the requirement should be added to the help, as eman2 is not required for Scipion in general. Alternatively this could be done in Xmipp

**Comment by azazellochg** [comment]
Thanks! I have added the explanation to help.
