### ISSUE TITLE
In relion 3D classification Tau fudge cannot be a decimal numbered value

### ISSUE THREAD

**Issue by JuhaHuiskonen** [scipion-em/scipion-em-relion#254]
In some special cases, it may be beneficial to change the "tau fudge value" and sometimes to values smaller than 1, e.g. 0.1.  Now it seems the GUI converts the value as integer. Value of 0.1 becomes 0.

**Comment by azazellochg** [comment]
Hi @JuhaHuiskonen , thanks. Luckily, the change from Int to Float is compatible with old projects (the other way around would be breaking), so I fixed this in the devel branch.
