### ISSUE TITLE
extract particle coordinates from 2D class

### ISSUE THREAD

**Issue by CFDavidHou** [scipion-em/scipion-em-relion#260]
Hi all,

I encountered an issue that I can't find answers elsewhere. I jump from RELION3.1 to Scipion3. In scipion3 how do you extract downscaled 2D class particles coordinates and re-extract again to have the original resolution particles? Or I can do it till I have finished initial model -> 3D class.

I am really need some help here.

Thank you!

David

**Comment by azazellochg** [comment]
Hello @CFDavidHou , you need to use "pwem - extract coordinates" protocol with "apply shifts" option.

**Comment by CFDavidHou** [comment]
I have hard time finding the "pwem - extract coordinates" I am using scipion3.0.7

And I can't find it in the plugin manager as well.

Thanks!

**Comment by azazellochg** [comment]
![image](https://user-images.githubusercontent.com/6952870/102555793-66a5b880-40bf-11eb-9052-923d774d7462.png)

**Comment by CFDavidHou** [comment]
Thank you azazellochg! found it!
