### ISSUE TITLE
RELION 3D refinement model issue 

### ISSUE THREAD

**Issue by AlazzawiAdil** [scipion-em/scipion-em-relion#265]
Hi,

  I'm trying to use RELION 3D refinement model with ribosome data, unfortunately I got the following error:

![1](https://user-images.githubusercontent.com/38712332/103729021-14143980-4fa5-11eb-911e-2112f7163848.png)
![2](https://user-images.githubusercontent.com/38712332/103729025-16769380-4fa5-11eb-90fb-c0141ef72718.png)
![3](https://user-images.githubusercontent.com/38712332/103729029-17a7c080-4fa5-11eb-882a-5e3137e859a3.png)
![4](https://user-images.githubusercontent.com/38712332/103729033-18d8ed80-4fa5-11eb-97d9-34b5a4e23e49.png)

Any suggestions please, really appreciate your help.

**Comment by azazellochg** [comment]
Hi @AlazzawiAdil , you are running refinement with 3 MPI and 1 thread and running out of GPU memory. You should use as many threads as you can (2*X threads=N, where N is the total number of CPU cores)

**Comment by AlazzawiAdil** [comment]
thanks @azazellochg for your response, in this case, if I have the following system which numbers should I used for both MPI and threads?

![4](https://user-images.githubusercontent.com/38712332/103786683-51f37b00-5002-11eb-9783-316bccec447f.png)

**Comment by azazellochg** [comment]
oops, I missed the fact that you are running on gpu. My previous comment is for cpu run. So, you run on a single machine? Depending on how many GPUs you have, I would use 2 threads per GPU

**Comment by azazellochg** [comment]
See https://www3.mrc-lmb.cam.ac.uk/relion/index.php/Benchmarks_%26_computer_hardware#Typical_GPU_usage

**Comment by AlazzawiAdil** [comment]
I have one GPU on a single machine in this case you mean I have to use 1 for MPI what about the number of threads in my case? appreciate your help

**Comment by AlazzawiAdil** [comment]
Ok I get it so that means MPI=1 and threads=2, am I correct?

**Comment by azazellochg** [comment]
you cannot use less than 3 MPIs for 3d refinement. Try 3x2. If you still run out of memory, reduce your box size or try  try "combine iterations through disc: Yes"

**Comment by AlazzawiAdil** [comment]
I will try thanks so much

**Comment by azazellochg** [comment]
If this doesn't help then try running your job on CPU with 3 mpi x 4 threads. For more information see relion tutorial, wiki and ccpem mailing list. The errors you are having are from Relion and not Scipion-related.

**Comment by AlazzawiAdil** [comment]
it does not I will try the CPU and see thanks
