### ISSUE TITLE
add threads option for relion localres function

### ISSUE THREAD

**Issue by andreanans** [scipion-em/scipion-em-relion#273]
Could you please add a 'threads' box in addition to the MPIs? In Relion standalone we can use a combination of MPIs and threads for Relion local resolution jobs. Using all MPIs is causing issues on our cluster..

Thank you!

Andrea

**Comment by azazellochg** [comment]
Hi Andrea, I just got a reply from Takanori saying that relion localres does not support threads. Also, if you check the command line in Relion GUI, number of threads is not translated into anything (there's no --j parameter).
