### ISSUE TITLE
gain reference not listed in .star files for polishing

### ISSUE THREAD

**Issue by andreanans** [scipion-em/scipion-em-relion#274]
I've updated to the latest version of the relion plugin and the gain reference is not listed in the input star files that are generated during Step 1 for polishing. Instead it lists "":

_rlnMicrographPreExposure                   0.0
_rlnVoltage                               300.0
_rlnMicrographStartFrame                      1
_rlnMotionModelVersion                        0
_rlnMicrographGainName                       ""
_rlnMicrographDefectFile                     ""

**Comment by azazellochg** [comment]
Hi @andreanans , currently you have to "assign" gain reference to aligned movies using assign optics groups protocol and then run polishing.

**Comment by andreanans** [comment]
OK, good to know. It would be useful to point a note somewhere in the polishing window so users know they must do this.

**Comment by azazellochg** [comment]
Added the following warning: "If you have provided a gain reference or defects file during '
                    'movie import or motion correction, please *make sure to '
                    'run first "assign optics groups" protocol for aligned '
                    'movies*, specifying the gain file etc. Currently, Scipion '
                    'has no other way of knowing if you have e.g. rotated the '
                    'gain during motion correction.\n\nOutput movies then can be '
                    'used in this polishing protocol.'
