### ISSUE TITLE
bayesian polishing listed as bayesian polishing training and vice versa

### ISSUE THREAD

**Issue by andreanans** [scipion-em/scipion-em-relion#275]
After updating to the latest relion plugin, I noticed that my bayesian polishing training jobs are labelled 'bayesian polishing' and my bayesian polishing jobs are labelled 'bayesian polishing training.'

**Comment by azazellochg** [comment]
I'm not sure I understand this. The protocol labels can be changed only by user, even the default ones as they are stored in db and not accessed by plugin.

**Comment by andreanans** [comment]
Apologies, you are correct. I forgot I had manually added 'training' to my polishing protocol labels to distinguish the training protocols from the polishing protocols.
