### ISSUE TITLE
Import particles not storing the acquisition info properly.

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-relion#294]
**Describe the bug**
When importing a start file in the import particles protocol ("relion" mode) the acquisition is not stored properly

**To Reproduce**
Steps to reproduce the behaviour:
1. Add import particles protocol
2. choose option "relion"
3. chose a star file from relion3.1 (we have tested using one from the dataset: data/tests/relion31_tutorial_precalculated/Class2D/job013/run_it025_data.star)
4. Acquisition object is not populated, not at set level nor at item level 

**Desktop (please complete the following information):**
 - Scipion version: [devel branches]
 - Relion plugin version [ branch [devel]

**Additional context**
Wizard gets the values right.

Here, Acquisition is populated correctly (we printed it) https://github.com/scipion-em/scipion-em-relion/blob/master/relion/convert/dataimport.py#L102

Here, Acquisition is overwritten --> https://github.com/scipion-em/scipion-em-relion/blob/c116c9f3c1ece66e6c62118f34aeecc2da2a0187/relion/convert/convert31.py#L545

![image](https://user-images.githubusercontent.com/785633/115447530-e46a0400-a218-11eb-964a-b4b5061432dc.png)

**Comment by azazellochg** [comment]
Hm, it looks like it's been like this at least for a year. We stopped using acquisition and use optics now. I'll fix it

**Comment by azazellochg** [comment]
I found the following from @delarosatrevin : 
```
# JMRT: Ideally I would like to disable the whole Acquisition for each
        #       particle row, but the SetOfImages will set it again.
        #       Another option could be to disable in the set, but then in
        #       streaming, other protocols might get the wrong optics info
```
@delarosatrevin do you recall this?

**Comment by delarosatrevin** [comment]
I think this is a performance note, since we know the optics group for each particle, we can know their Acquisition without storing it per particle. It will save many columns per row.

**Comment by azazellochg** [comment]
for the readSetOfParticles readAcquisition=True is used only in the dataimport, however this flag is ignored and convert31 has partSet.setAcquisition(acq) with zeros - default values every time.

**Comment by azazellochg** [comment]
@pconesa do you have time to check the fix in devel branch?

**Comment by pconesa** [comment]
Sure.

**Comment by pconesa** [comment]
![image](https://user-images.githubusercontent.com/785633/116698040-356dbb00-a9c4-11eb-89c0-fb7808b3b8e4.png)
I can see acquisition values now and running cryosparc 2d classification with relion imported particles  worked. 

I'd say is fixed. Thank you!
