### ISSUE TITLE
do manual grouping ctfs

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#30]
Hi,

   I am trying to run relion 3 inside Scipion using this plugin (branch relion3). In the CTF tab there is an option called "Do manual grouping CTFs", if yes is selected two extra options should appear, defocus range and minimum size. 

  In the new version this options are gone :-(. Can you put then back?

    Roberto

**Comment by azazellochg** [comment]
they are there: https://github.com/scipion-em/scipion-em-relion/blob/relion3/relion/protocols/protocol_base.py#L383
