### ISSUE TITLE
Import coordinates from particles.star

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-relion#301]
**Is your feature request related to a problem? Please describe.**
In several occasions, users wanted to import a particles.star file (coming from refinements) done outside scipion with relion or CS. But they are interested only in getting the coordinates.

Generic Import coordinates does not fit in this approach since it expects having  1 metadata file per coordinate file.

**Describe the solution you'd like**
A dedicated "relion import coordinates" protocol to deal with particles.star files

**Describe alternatives you've considered**
Another option might be to use import particles, maybe skipping missing binaries, which for this case are not needed?

Thoughts?

**Comment by azazellochg** [comment]
@pconesa you want to import a single particles star file, right?

**Comment by pconesa** [comment]
Yes,that would be the idea. Just a particle star file. 
Obviously the challenge there would be to do the matching against an existing setOfMicrographs based on micname== rlnMIcrographName (or whatever appropriate field name).

**Comment by azazellochg** [comment]
Hi Pablo, you can test
it now on devel, I'll release on pypi soon
