### ISSUE TITLE
relion does not support filenames starting with "_"

### ISSUE THREAD

**Issue by DStrelak** [scipion-em/scipion-em-relion#311]
**Describe the bug**
ERROR: Extra work (i.e plots, PSD, thumbnail) has failed 
Movie alignment failed completely

**To Reproduce**
1. using https://www.ebi.ac.uk/empiar/EMPIAR-10591/
_20190614_160652.mrc 1.3 GB
_20190614_161552.mrc 1.3 GB
_20190614_161931.mrc 1.3 GB
2. Import them
3. Try to align them with relion motion correction (setting Number of patches to 4x4):
```
00022:   STARTED: processMovieStep, step 2, time 2021-08-23 11:44:21.088462
00023:   Processing movie: Runs/000230_ProtRelionMotioncor/tmp/movie_000001/_20190614_160652.mrc
00024:    relion_run_motioncorr --i _20190614_160652_input.star --o output/ --use_own --first_frame_sum 1 --last_frame_sum 40 --bin_factor 1.000000 --bfactor 150 --angpix 0.49200 --patch_x 4 --patch_y 4 --group_frames 1 --j 4  
00025:    + WARNING: will ignore (but maintain) values for the unknown label: 20190614_160652.mrc 1 1
00026:    Using our own implementation based on MOTIONCOR2 algorithm
00027:    to correct beam-induced motion for the following micrographs: 
00028:    Correcting beam-induced motions using our own implementation ...
00029:    Generating logfile.pdf ... 
00030:    Did not find any of the expected EPS files to generate a PDF file
00031:    + Will make an empty PDF-file in output/logfile.pdf
00032:    Done! Written: output/logfile.pdf and output/corrected_micrographs.star
00033:   ERROR: Extra work (i.e plots, PSD, thumbnail) has failed for _20190614_160652.mrc
00034:   
00035:   ERROR processing movie:  _20190614_160652.mrc
00036:   Erasing.....movieFolder: Runs/000230_ProtRelionMotioncor/tmp/movie_000001
00037:   FINISHED: processMovieStep, step 2, time 2021-08-23 11:44:21.127306
```
**Expected behavior**
Movies are correctly processed

**Screenshots**
![image](https://user-images.githubusercontent.com/28389367/130427033-612be00d-5edc-4a17-953f-9639e56b2f23.png)
![image](https://user-images.githubusercontent.com/28389367/130427125-19c67e8f-af86-4a7a-b889-5abefce8e3ab.png)

**Logs**
./scipion3
Scipion v3.0.8 - Eugenius
The package scipion-pyworkflow is out of date. Your version is 3.0.16, the latest is 3.0.17.
The package scipion-em is out of date. Your version is 3.0.11, the latest is 3.0.13.
The package scipion-app is out of date. Your version is 3.0.8, the latest is 3.0.9.
Scipion-em-relion v. 3.1.3

**Comment by azazellochg** [comment]
@DStrelak relion does not support filenames starting with "_", as this is reserved for star labels.

**Comment by DStrelak** [comment]
> @DStrelak relion does not support filenames starting with "_", as this is reserved for star labels.

In that case, the plugin should either check the name and change it accordingly, or at least show some reasonable error message
