### ISSUE TITLE
autorefine fails if  mask extension is map

### ISSUE THREAD

**Issue by rmarabinipsi** [scipion-em/scipion-em-relion#312]
**Describe the bug**
when running autorefine the first command executed is: 

00016:   ** Running command:  relion_image_handler --i Runs/028693_ProtImportMask/extra/maskSmall_120_23_08_2021_2.mrc --o Runs/028732_ProtRelionRefine3D/tmp/maskSmall_120_23_08_2021_2.mrc --angpix 1.38000 --new_box 120 --threshold_above 1 --threshold_below 0

if the extension of the input image is "map" the program fails, if the very same image is used with extension "mrc" the protocol finishes.

"versions"
scipion-em-relion: last devel 
    commit 36e5f0323f101c108eff421efa53ee0a220ad539 (HEAD -> devel, origin/devel)
Author: Grigory Sharov <sharov.grigory@gmail.com>
Date:   Tue Aug 31 15:04:15 2021 +0100

relion binaries, compiled using gcc-7, version: relion-3.1.0

**Logs**00002:   ERROR: 
00003:   Error in askMemory: Memory allocation size requested is zero!
00004:   === Backtrace  ===
00005:   relion_image_handler(_ZN11RelionErrorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x67) [0x5642dce95617]
00006:   relion_image_handler(_Z9askMemorym+0x75) [0x5642dceb4605]
00007:   relion_image_handler(_ZN5ImageIdE8readDataEP8_IO_FILEl8DataTypem+0xa9) [0x5642dce79cd9]
00008:   relion_image_handler(_ZN5ImageIdE10readSPIDEREl+0x316) [0x5642dce7d1b6]
00009:   relion_image_handler(_ZN5ImageIdE5_readERK8FileNameR13fImageHandlerblbb+0x114) [0x5642dce7ff44]
00010:   relion_image_handler(+0x8d303) [0x5642dce82303]
00011:   relion_image_handler(_ZN24image_handler_parameters3runEv+0x319e) [0x5642dce8ce7e]
00012:   relion_image_handler(main+0x34) [0x5642dce6af54]
00013:   /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f640d4f909b]
00014:   relion_image_handler(_start+0x2a) [0x5642dce6e20a]
00015:   ==================
00016:   ERROR: 
00017:   Error in askMemory: Memory allocation size requested is zero!
00018:   Traceback (most recent call last):
00019:     File "/home/roberto/scipion3/.scipion3/lib/python3.7/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
00020:       self._run()
00021:     File "/home/roberto/scipion3/.scipion3/lib/python3.7/site-packages/pyworkflow/protocol/protocol.py", line 1360, in _run
00022:       self._insertAllSteps()  # Define steps for execute later
00023:     File "/home/roberto/scipion3/Plugins/scipion-em-relion/relion/protocols/protocol_base.py", line 814, in _insertAllSteps
00024:       self._insertRelionStep()
00025:     File "/home/roberto/scipion3/Plugins/scipion-em-relion/relion/protocols/protocol_base.py", line 825, in _insertRelionStep
00026:       self._setNormalArgs(args)
00027:     File "/home/roberto/scipion3/Plugins/scipion-em-relion/relion/protocols/protocol_base.py", line 1044, in _setNormalArgs
00028:       self._setBasicArgs(args)
00029:     File "/home/roberto/scipion3/Plugins/scipion-em-relion/relion/protocols/protocol_base.py", line 1113, in _setBasicArgs
00030:       self._setMaskArgs(args)
00031:     File "/home/roberto/scipion3/Plugins/scipion-em-relion/relion/protocols/protocol_base.py", line 1141, in _setMaskArgs
00032:       tmp, newPix, newDim)
00033:     File "/home/roberto/scipion3/Plugins/scipion-em-relion/relion/convert/convert_utils.py", line 224, in convertMask
00034:       pwutils.runJob(None, 'relion_image_handler', params, env=Plugin.getEnviron())
00035:     File "/home/roberto/scipion3/.scipion3/lib/python3.7/site-packages/pyworkflow/utils/process.py", line 52, in runJob
00036:       return runCommand(command, env, cwd)
00037:     File "/home/roberto/scipion3/.scipion3/lib/python3.7/site-packages/pyworkflow/utils/process.py", line 68, in runCommand
00038:       env=env, cwd=cwd)
00039:     File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
00040:       raise CalledProcessError(retcode, cmd)
00041:   subprocess.CalledProcessError: Command ' relion_image_handler --i Runs/029049_ProtImportMask/extra/maskSmall_120_23_08_2021_2.map --o Runs/029086_ProtRelionRefine3D/tmp/maskSmall_120_23_08_2021_2.mrc --angpix 1.38000 --new_box 120 --threshold_above 1 --threshold_below 0' returned non-zero exit status 1.

**Comment by azazellochg** [comment]
Hi @rmarabinipsi , thanks for reporting the bug. Can you pull the branch again and test? It should be fixed.

**Comment by rmarabinipsi** [comment]
hi @azazellochg ,

      I works now ;-)

       Thanks
