### ISSUE TITLE
Shift plot wrong when skiping first frame in alignment

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-relion#314]
This is what I'm getting when I skip the first frame. I think the first dot should not be there.
![image](https://user-images.githubusercontent.com/785633/132499927-78b1ac11-a6b6-4e48-8265-80733d57c7b9.png)

**Comment by azazellochg** [comment]
Good catch! The frames that have no/zero shifts are assigned with -9999px shifts. I'll fix the plot.

**Comment by azazellochg** [comment]
Fixed in https://github.com/scipion-em/scipion-em-relion/commit/31d63ad5f95bb9a1fb4b98266dc5c9f4ce1ed4ce and https://github.com/scipion-em/scipion-em-relion/commit/0ea2fcd2bd758f4751a66f6014731bca8d5e734d
