### ISSUE TITLE
Relion - auto-picking LoG fail - unknown "--pickname""

### ISSUE THREAD

**Issue by FraaaMazzz** [scipion-em/scipion-em-relion#317]
I have obtained my micrographs  and I now want to pick the particles for SPA.
So I launch **Relion - auto-picking LoG** but it fails immediately. 

I'm working with Scipion v3.0.9 

run.stdout

_00047:   Logging configured. STDOUT --> Runs/001888_ProtRelionAutopickLoG/logs/run.stdout , STDERR --> Runs/001888_ProtRelionAutopickLoG/logs/run.stderr
00048:   RUNNING PROTOCOL -----------------
00049:   Protocol starts
00050:   Hostname: Cryo-EM-Worktsation
00051:   PID: 41947
00052:   pyworkflow: 3.0.17
00053:   plugin: relion
00054:   plugin v: 3.1.3
00055:   currentDir: /home/em-group/ScipionUserData/Mazzotta/ApoFer
00056:   workingDir: Runs/001888_ProtRelionAutopickLoG
00057:   runMode: Continue
00058:             MPI: 4
00059:         threads: 1
00060:    Starting at step: 1
00061:    Running steps 
00062:   STARTED: pickMicrographStep, step 1, time 2021-10-19 13:33:00.458358
00063:   Picking micrograph: Runs/000655_XmippProtMovieCorr/extra/190117_02_00001_UnderDefocus0.7um_frameImage_aligned_mic.mrc 
00064:   Some paths do not exist in: /usr/local/cuda-10.1/lib64
00065:    mpirun -np 4  `which relion_autopick_mpi`  --pickname autopick --odir "./" --LoG --shrink 0 --lowpass 20.000  --i input_micrographs.star --LoG_diam_min 100.000 --LoG_diam_max 200.000 --LoG_adjust_threshold 0.000 --LoG_upper_threshold 999.000
00066:   Protocol failed: Command ' mpirun -np 4  `which relion_autopick_mpi`  --pickname autopick --odir "./" --LoG --shrink 0 --lowpass 20.000  --i input_micrographs.star --LoG_diam_min 100.000 --LoG_diam_max 200.000 --LoG_adjust_threshold 0.000 --LoG_upper_threshold 999.000' returned non-zero exit status 1.
00067:   FAILED: pickMicrographStep, step 1, time 2021-10-19 13:33:00.481998
00068:   *** Last status is failed 
00069:   ------------------- PROTOCOL FAILED (DONE 1/21)_

run.stderr

_00059:   mpirun: Error: unknown option "--pickname"
00060:   Type 'mpirun --help' for usage.
00061:   Traceback (most recent call last):
00062:     File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
00063:       self._run()
00064:     File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 252, in _run
00065:       resultFiles = self._runFunc()
00066:     File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _runFunc
00067:       return self._func(*self._args)
00068:     File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_particles_picking.py", line 241, in pickMicrographStep
00069:       self._pickMicrograph(mic, *args)
00070:     File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/relion/protocols/protocol_autopick.py", line 44, in _pickMicrograph
00071:       self._pickMicrographList([mic], *args)
00072:     File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/relion/protocols/protocol_autopick.py", line 54, in _pickMicrographList
00073:       self._pickMicrographsFromStar(micStar, micsDir, *args)
00074:     File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/relion/protocols/protocol_autopick_log.py", line 161, in _pickMicrographsFromStar
00075:       self.runJob(program, params, cwd=cwd)
00076:     File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1388, in runJob
00077:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00078:     File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
00079:       process.runJob(log, programName, params,
00080:     File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 52, in runJob
00081:       return runCommand(command, env, cwd)
00082:     File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 67, in runCommand
00083:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
00084:     File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
00085:       raise CalledProcessError(retcode, cmd)
00086:   subprocess.CalledProcessError: Command ' mpirun -np 4  `which relion_autopick_mpi`  --pickname autopick --odir "./" --LoG --shrink 0 --lowpass 20.000  --i input_micrographs.star --LoG_diam_min 100.000 --LoG_diam_max 200.000 --LoG_adjust_threshold 0.000 --LoG_upper_threshold 999.000' returned non-zero exit status 1.
00087:   Protocol failed: Command ' mpirun -np 4  `which relion_autopick_mpi`  --pickname autopick --odir "./" --LoG --shrink 0 --lowpass 20.000  --i input_micrographs.star --LoG_diam_min 100.000 --LoG_diam_max 200.000 --LoG_adjust_threshold 0.000 --LoG_upper_threshold 999.000' returned non-zero exit status 1._

Can you help me understand what I'm doing wrong?

**Comment by FraaaMazzz** [comment]
I think I have successfully and correctly installed Relion, I have even specified the relion location in scipion.conf, but I still get the `mpirun: Error: unknown option "--pickname"`

**Comment by FraaaMazzz** [comment]
1) scipion3 config -p relion

Scipion v3.0.9 - Eugenius
Variables defined by plugin 'relion':

RELION_HOME = /home/em-group/Programs/software/em/relion-4.0/
RELION_CUDA_LIB = /usr/local/cuda-11.4/lib64
RELION_PYTHON = None

These variables can be added/edited in '/home/em-group/Programs/config/scipion.conf'

2) scipion3 run relion_refine --version
Scipion v3.0.9 - Eugenius
relion command detected
** Running command:  relion_refine "--version"
/bin/sh: 1: relion_refine: not found
Traceback (most recent call last):
  File "/home/em-group/miniconda3/envs/scipion3/bin/emprogram", line 8, in <module>
    sys.exit(main())
  File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/pwem/cmd/program.py", line 43, in main
    runProgram(program, params)
  File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/pwem/utils.py", line 69, in runProgram
    pwutils.runJob(None, program, params, env=env)
  File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 52, in runJob
    return runCommand(command, env, cwd)
  File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 67, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
  File "/home/em-group/miniconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' relion_refine "--version"' returned non-zero exit status 127.

3) mpirun -np 4 hostname
Invalid MIT-MAGIC-COOKIE-1 keyCryo-EM-Worktsation
Cryo-EM-Worktsation
Cryo-EM-Worktsation
Cryo-EM-Worktsation

**Comment by azazellochg** [comment]
Oh well, you have not installed relion binaries correctly then. Did you clone the git repo as per instructions?

**Comment by azazellochg** [comment]
Great! You are welcome
