### ISSUE TITLE
self.realignMovieFrames

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#32]
Still trying to run relion3 (branch relion3)

If I execute  relion 3D - autorefine I get the error:

----
00023:     File "/usr/local/Plugins/scipion-em-relion/relion/protocols/protocol_refine3d.py", line 85, in _setSamplingArgs
00024:       if self.realignMovieFrames:
00025:   AttributeError: 'ProtRelionRefine3D' object has no attribute 'realignMovieFrames'
---- 

  In file file "protocol_refine3d.py" line 85 there is a conditional:

              if self.realignMovieFrames:

realignMovieFrames is defined in protocol_base.py
---
                if not self.IS_V3:
                    form.addSection("Movies")
                    form.addParam('realignMovieFrames', BooleanParam, default=False
---

bur only gets defined if you are not using relion 3.

Am I missing something here?

  Roberto

**Comment by azazellochg** [comment]
Thanks @rmarabini ! I have fixed this.
