### ISSUE TITLE
3D Classification error in Relion 4.0 plugin

### ISSUE THREAD

**Issue by cossorzano** [scipion-em/scipion-em-relion#325]
In a 3D classification within Scipion using Relion-4.0 I get the following error just when constructing the output

01530:   FINISHED: runRelionStep, step 2, time 2022-02-13 06:07:15.700761
01531:   STARTED: createOutputStep, step 3, time 2022-02-13 06:07:15.724766
01532:   types:  [<class 'int'>, <class 'float'>, <class 'float'>, <class 'int'>, <class 'str'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'int'>, <class 'int'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'int'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'int'>]
01533:   values:  ['8', '450.000000', '3414.000000', '190808_120kx_40fr_50e_FoilHole_5912387_Data_5942246_5942247_20190809_0819_Fractions.mrc', '000008@Runs/007089_ProtRelionClassify3D/extra/input/190808_120kx_40fr_50e_FoilHole_5912387_Data_5942246_5942247_20190809_0819_Fractions_aligned_mic_DW.mrcs', '3256.940000', '2935.580000', '321.360000', '58.558800', '0.168554', '1.804000', '1', '4', '88.523737', '35.828957', '-89.26008', '8.106496', '-0.74950', '1', '0.822513', '50569.279432', '0.783293', '181']
01534:   Protocol failed: invalid literal for int() with base 10: '190808_120kx_40fr_50e_FoilHole_5912387_Data_5942246_5942247_20190809_0819_Fractions.mrc'
01535:   FAILED: createOutputStep, step 3, time 2022-02-13 06:07:15.741556

It seems that the format of the star file is not the one expected by the protocol. At the moment, I am stuck with this processing and a fix or a suggestion how to recover this output would be appreciated.

Thanks.

**Comment by cossorzano** [comment]
I tried to, but which file exactly?

**Comment by delarosatrevin** [comment]
I'm not entirely sure, but I think it is the last particles star file
generated by the relion program.

**Comment by cossorzano** [comment]
The last file is relion_it025_data.star. The beginning of the particles block is

# version 30001

data_particles

loop_ 
_rlnImageId #1 
_rlnCoordinateX #2 
_rlnCoordinateY #3 
_rlnMicrographName #4 
_rlnImageName #5 
_rlnDefocusU #6 
_rlnDefocusV #7 
_rlnCtfAstigmatism #8 
_rlnDefocusAngle #9 
_rlnCtfFigureOfMerit #10 
_rlnCtfMaxResolution #11 
_rlnOpticsGroup #12 
_rlnGroupNumber #13 
_rlnAngleRot #14 
_rlnAngleTilt #15 
_rlnAnglePsi #16 
_rlnOriginXAngst #17 
_rlnOriginYAngst #18 
_rlnClassNumber #19 
_rlnNormCorrection #20 
_rlnLogLikeliContribution #21 
_rlnMaxValueProbDistribution #22 
_rlnNrOfSignificantSamples #23 
      100123   544.000000  1260.000000       1398 000001@Runs/007089_ProtRelionClassify3D/extra/input/190829_120kx_40fr_50e_FoilHole_29731128_Data_29757645_29757647_20190830_
0205_Fractions_aligned_mic_DW.mrcs  7141.620000  7060.370000    81.250000    19.815300     0.150095     0.984000            1            1    95.358172    29.245222   125.679
286     6.630496     -3.70150            1     0.841682 50497.925875     0.738025           24 

The line that fails is
           8   450.000000  3414.000000 190808_120kx_40fr_50e_FoilHole_5912387_Data_5942246_5942247_20190809_0819_Fractions.mrc 000008@Runs/007089_ProtRelionClassify3D/extra/input/190808_120kx_40fr_50e_FoilHole_5912387_Data_5942246_5942247_20190809_0819_Fractions_aligned_mic_DW.mrcs  3256.940000  2935.580000   321.360000    58.558800     0.168554     1.804000            1            4    88.523737    35.828957    -89.26008     8.106496     -0.74950            1     0.822513 50569.279432     0.783293          181 

The previous line is

      919496  1176.000000    91.000000      19066 000088@Runs/007089_ProtRelionClassify3D/extra/input/191123_120kx_40fr_50e_FoilHole_25175436_Data_24130499_24130501_20191124_
0256_Fractions_aligned_mic_DW.mrcs 14893.400000 14508.300000   385.100000    41.766500     0.140091     3.044250            1            3   134.896946    17.942668    24.863
383     -0.74950     -2.22550            1     0.846087 50571.501617     0.999388            3 

which certainly has a different structure (the fourth field is a number). Interestingly, the first particle in input_particles.star is the image that causes the failure.

data_particles

loop_
_rlnImageId 
_rlnCoordinateX 
_rlnCoordinateY 
_rlnMicrographName 
_rlnImageName 
_rlnDefocusU 
_rlnDefocusV 
_rlnCtfAstigmatism 
_rlnDefocusAngle 
_rlnCtfFigureOfMerit 
_rlnCtfMaxResolution 
_rlnOpticsGroup 
 8   450   3414   190808_120kx_40fr_50e_FoilHole_5912387_Data_5942246_5942247_20190809_0819_Fractions.mrc   000008@Runs/007089_ProtRelionClassify3D/extra/input/190808_120kx_4
0fr_50e_FoilHole_5912387_Data_5942246_5942247_20190809_0819_Fractions_aligned_mic_DW.mrcs   3256.940000   2935.580000   321.360000   58.558800   0.168554   1.804000   1 

Thanks a lot, Carlos Oscar

**Comment by azazellochg** [comment]
Quite an interesting case where micname=micid for some particles and not for others.

**Comment by azazellochg** [comment]
@delarosatrevin I don't see an easy way to solve this. We could change micName = "mic_" + micId, but that does not guarantee that other plugins will do the same. Instead of guessing type in emtable from the first line maybe it's better to have a dict of label:type? For unknown labels we would put the string type by default.

**Comment by cossorzano** [comment]
Dear both, do you think you can produce any solution to save this analysis, in particular, and to avoid similar situations in the future?

**Comment by azazellochg** [comment]
Hi @cossorzano, until a proper solution is implemented, a quick hack would be to make https://github.com/3dem/emtable/blob/d3117462b83bf2927c6b5f7697e8ca883fe3a623/emtable/metadata.py#L530 always return str

**Comment by cossorzano** [comment]
Thank you, Grigory. I could, at least, construct an output. Cheers.

**Comment by azazellochg** [comment]
Fixed in devel and new emtable release
