### ISSUE TITLE
Error in  Relion particle extraction

### ISSUE THREAD

**Issue by Adriaj95** [scipion-em/scipion-em-relion#326]
When I perform particle extraction after autopicking with relion it appears an error that stops the program when finishes the step 1. The error says "local variable 'posSet' referenced before assignment". I don't know what does it mean nor what to change to make it work.

The parameters of particle extraction are the ones in the images i attach.

I also copied the run.stdout log file of the protocol.

Thank you in advance

Adrià.
![IMG-5453](https://user-images.githubusercontent.com/99664048/154032985-b6a0b783-b91d-4514-9925-c607ca6cd329.jpg)
![IMG-5454](https://user-images.githubusercontent.com/99664048/154033037-2f23e5cb-995c-40ce-8641-cfab2dd84101.jpg)

**Desktop (please complete the following information):**
 - Scipion version: [2.0 ]
 - Relion plugin version 1.0.9 

**Additional context**

When I perform the first particle picking with xmipp, I can do particle extraction with relion without problems and go for 2D classification in Relion. Thus, when I perform template based picking with relion autopicking adding the 2d averages, i can not extract the particles with relion extract pa
![IMG-5453](https://user-images.githubusercontent.com/99664048/154032720-26f58cf6-481f-4c42-91a3-1cd24ef6e626.jpg)
![IMG-5454](https://user-images.githubusercontent.com/99664048/154032778-4a51f88b-10a5-4eb0-9d33-a4f22eee5518.jpg)
rticles. 

00001:   RUNNING PROTOCOL -----------------
00002:        HostName: cri1-vixion
00003:             PID: 78785
00004:         Scipion: v2.0 (2019-04-23) Diocletian
00005:      currentDir: /data/aajcri/ScipionUserData/projects/RNAPholo Adria
00006:      workingDir: Runs/013047_ProtRelionExtractParticles
00007:         runMode: Continue
00008:             MPI: 10
00009:         threads: 1
00010:   0:00:00.747196 reading coordinates for mic number 000050
...
00030:   WARNING: The batch size of 1 does not make sense when not in streaming...changed value to 0 (extract all).
00031:   len(steps) 2 len(prevSteps) 0
00032:    Starting at step: 1
00033:    Running steps
00034:   STARTED: extractMicrographListStep, step 1
00035:     2022-02-11 14:15:12.026683
00036:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002312_Data_FoilHole_1004752_Data_984973_984975_20211202_044520_Fractions_aligned_mic_DW.mrc
00037:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002312_Data_FoilHole_1004753_Data_984958_984960_20211202_045101_Fractions_
00303:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004079_Data_984964_984966_20211202_021132_Fractions_aligned_mic_DW.mrc
00304:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004079_Data_984967_984969_20211202_021215_Fractions_aligned_mic_DW.mrc
00305:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004079_Data_984970_984972_20211202_021258_Fractions_aligned_mic_DW.mrc
00306:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004079_Data_984973_984975_20211202_021341_Fractions_aligned_mic_DW.mrc
00307:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004080_Data_984958_984960_20211202_021922_Fractions_aligned_mic_DW.mrc
00308:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004080_Data_984964_984966_20211202_021630_Fractions_aligned_mic_DW.mrc
00309:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004080_Data_984967_984969_20211202_021713_Fractions_aligned_mic_DW.mrc
00310:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004080_Data_984970_984972_20211202_021756_Fractions_aligned_mic_DW.mrc
00311:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004080_Data_984973_984975_20211202_021839_Fractions_aligned_mic_DW.mrc
00312:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004081_Data_984958_984960_20211202_022417_Fractions_aligned_mic_DW.mrc
00313:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004081_Data_984961_984963_20211202_022500_Fractions_aligned_mic_DW.mrc
00314:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004081_Data_984964_984966_20211202_022125_Fractions_aligned_mic_DW.mrc
00315:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004081_Data_984967_984969_20211202_022208_Fractions_aligned_mic_DW.mrc
00316:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004081_Data_984970_984972_20211202_022251_Fractions_aligned_mic_DW.mrc
00317:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004081_Data_984973_984975_20211202_022334_Fractions_aligned_mic_DW.mrc
00318:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004082_Data_984958_984960_20211202_022912_Fractions_aligned_mic_DW.mrc
00319:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004082_Data_984961_984963_20211202_022955_Fractions_aligned_mic_DW.mrc
00320:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004082_Data_984964_984966_20211202_022620_Fractions_aligned_mic_DW.mrc
00321:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004082_Data_984970_984972_20211202_022746_Fractions_aligned_mic_DW.mrc
00322:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004082_Data_984973_984975_20211202_022829_Fractions_aligned_mic_DW.mrc
00323:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004083_Data_984958_984960_20211202_023408_Fractions_aligned_mic_DW.mrc
00324:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004083_Data_984964_984966_20211202_023116_Fractions_aligned_mic_DW.mrc
00325:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004084_Data_984958_984960_20211202_023903_Fractions_aligned_mic_DW.mrc
00326:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004084_Data_984961_984963_20211202_023946_Fractions_aligned_mic_DW.mrc
00327:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004084_Data_984964_984966_20211202_023611_Fractions_aligned_mic_DW.mrc
00328:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004084_Data_984967_984969_20211202_023654_Fractions_aligned_mic_DW.mrc
00329:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004084_Data_984970_984972_20211202_023737_Fractions_aligned_mic_DW.mrc
00330:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004084_Data_984973_984975_20211202_023820_Fractions_aligned_mic_DW.mrc
00331:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004085_Data_984961_984963_20211202_024511_Fractions_aligned_mic_DW.mrc
00332:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004085_Data_984964_984966_20211202_024136_Fractions_aligned_mic_DW.mrc
00333:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004085_Data_984967_984969_20211202_024219_Fractions_aligned_mic_DW.mrc
00334:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004085_Data_984970_984972_20211202_024302_Fractions_aligned_mic_DW.mrc
00335:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004085_Data_984973_984975_20211202_024344_Fractions_aligned_mic_DW.mrc
00336:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004086_Data_984958_984960_20211202_024926_Fractions_aligned_mic_DW.mrc
00337:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004086_Data_984961_984963_20211202_025009_Fractions_aligned_mic_DW.mrc
00338:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004086_Data_984964_984966_20211202_024633_Fractions_aligned_mic_DW.mrc
00339:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004086_Data_984967_984969_20211202_024717_Fractions_aligned_mic_DW.mrc
00340:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004086_Data_984970_984972_20211202_024800_Fractions_aligned_mic_DW.mrc
00341:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004086_Data_984973_984975_20211202_024843_Fractions_aligned_mic_DW.mrc
00342:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1002318_Data_FoilHole_1004098_Data_984958_984960_20211202_025506_Fractions_aligned_mic_DW.mrc
...
01051:   Extracting micrograph: Runs/009212_ProtMotionCorr/extra/GridSquare_1003183_Data_FoilHole_1007092_Data_984973_984975_20211201_202058_Fractions_aligned_mic_DW.mrc
01052:   mpirun -np 10  `which relion_preprocess_mpi`  --i micrographs_00018-01236.star --part_star micrographs_00018-01236_particles.star  --coord_dir "." --coord_suffix .coords.star --part_dir "." --extract  --extract_size 320 --set_angpix 0.855000 --bg_radius 120 --invert_contrast --norm
01053:   /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi: /usr/local/scipion/v2.0.0/software/lib/libtiff.so.5: no version information available (required by /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi)
01054:   /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi: /usr/local/scipion/v2.0.0/software/lib/libtiff.so.5: no version information available (required by /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi)
01055:   /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi: /usr/local/scipion/v2.0.0/software/lib/libtiff.so.5: no version information available (required by /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi)
01056:   /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi: /usr/local/scipion/v2.0.0/software/lib/libtiff.so.5: no version information available (required by /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi)
01057:   /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi: /usr/local/scipion/v2.0.0/software/lib/libtiff.so.5: no version information available (required by /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi)
01058:   /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi: /usr/local/scipion/v2.0.0/software/lib/libtiff.so.5: no version information available (required by /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi)
01059:   /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi: /usr/local/scipion/v2.0.0/software/lib/libtiff.so.5: no version information available (required by /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi)
01060:   /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi: /usr/local/scipion/v2.0.0/software/lib/libtiff.so.5: no version information available (required by /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi)
01061:   /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi: /usr/local/scipion/v2.0.0/software/lib/libtiff.so.5: no version information available (required by /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi)
01062:   /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi: /usr/local/scipion/v2.0.0/software/lib/libtiff.so.5: no version information available (required by /usr/local/scipion/v2.0.0/software/em/relion-3.0/bin/relion_preprocess_mpi)
01063:    === RELION MPI setup ===
01064:    + Number of MPI processes             = 10
01065:    + Master  (0) runs on host            = cri1-vixion
01066:    + Slave     1 runs on host            = cri1-vixion
01067:    + Slave     2 runs on host            = cri1-vixion
01068:    + Slave     3 runs on host            = cri1-vixion
01069:    + Slave     4 runs on host            = cri1-vixion
01070:    + Slave     5 runs on host            = cri1-vixion
01071:    + Slave     6 runs on host            = cri1-vixion
01072:    + Slave     7 runs on host            = cri1-vixion
01073:    + Slave     8 runs on host            = cri1-vixion
01074:    + Slave     9 runs on host            = cri1-vixion
01075:    =================
01076:    + Setting pixel size in output STAR file to 0.855 Angstroms
01077:   WARNING: You manually changed the pixel size by the --set_angpix option. You can no longer use Bayesian Polishing on the resulting particles.
01078:    Extracting particles from the micrographs ...
01079:   4.22/4.22 min ............................................................~~(,_,">
01080:    Joining metadata of all particles from 1016 micrographs in one STAR file...
01081:    Written out STAR file with 208195 particles in micrographs_00018-01236_particles.star
01082:    The new pixel size of the extracted particles are 0.855 Angstrom/pixel.
01083:    Done preprocessing!
01084:   FINISHED: extractMicrographListStep, step 1
01085:     2022-02-11 14:19:56.820841
01086:   Traceback (most recent call last):
01087:     File "/usr/local/scipion/v2.0.0/pyworkflow/protocol/protocol.py", line 186, in run
01088:       self._run()
01089:     File "/usr/local/scipion/v2.0.0/pyworkflow/protocol/protocol.py", line 1289, in _run
01090:       self._runSteps(startIndex)
01091:     File "/usr/local/scipion/v2.0.0/pyworkflow/protocol/protocol.py", line 1161, in _runSteps
01092:       self._stepsCheckSecs)
01093:     File "/usr/local/scipion/v2.0.0/pyworkflow/protocol/executor.py", line 133, in runSteps
01094:       stepsCheckCallback()
01095:     File "/usr/local/scipion/v2.0.0/pyworkflow/em/protocol/protocol_particles.py", line 320, in _stepsCheck
01096:       self._checkNewOutput()
01097:     File "/usr/local/scipion/v2.0.0/pyworkflow/em/protocol/protocol_particles.py", line 527, in _checkNewOutput
01098:       self._updateOutputPartSet(newDone, streamMode)
01099:     File "/usr/local/scipion/v2.0.0/pyworkflow/em/protocol/protocol_particles.py", line 581, in _updateOutputPartSet
01100:       self.readPartsFromMics(micList, outputParts)
01101:     File "/usr/local/scipion/plugins/scipion-em-relion/relion/protocols/protocol_extract_particles.py", line 323, in readPartsFromMics
01102:       if pos in posSet:
01103:   UnboundLocalError: local variable 'posSet' referenced before assignment
01104:   ------------------- PROTOCOL FAILED (DONE 1/2)

**Comment by azazellochg** [comment]
Hi @Adriaj95 , I'm afraid Scipion2.0 nor Relion 3.0 are not supported anymore and there will be no bugfixes. You will have to upgrade
