### ISSUE TITLE
Error Relion  "returned non-zero exit status 127"

### ISSUE THREAD

**Issue by Adriaj95** [scipion-em/scipion-em-relion#329]
**Describe the bug**
When I try to run any Relion program (2D class, extract particles, motion corr etc.) it appears the error "returned non-zero exit status 127" and then the program doesn't work.

It happens with relion 4.0 but also in previous 3.1 version too.

**To Reproduce**
1. Go to 'Relion Motion Correction'
2. Click on 'Run'
3. Scroll down to 'run.stdout'
4. See error : returned non-zero exit status 127

**Logs**

run.stdout of Prot Relion MotionCorr but the same error appears in all other relion related runs.

00001:   Logging configured. STDOUT --> Runs/001473_ProtRelionMotioncor/logs/run.stdout , STDERR --> Runs/001473_ProtRelionMotioncor/logs/run.stderr
00002:   RUNNING PROTOCOL -----------------
00003:   Protocol starts
00004:   Hostname: cri1-vixion
00005:   PID: 29033
00006:   pyworkflow: 3.0.19
00007:   plugin: relion
00008:   plugin v: 4.0b8
00009:   currentDir: /data/aajcri/RNAP_Holo_DNA_Adria
00010:   workingDir: Runs/001473_ProtRelionMotioncor
00011:   runMode: Continue
00012:             MPI: 1
00013:         threads: 4
00014:    Starting at step: 1
00015:    Running steps
00016:   STARTED: _convertInputStep, step 1, time 2022-03-02 15:23:21.832586
00017:   Relion version:
00018:   Some paths do not exist in: /usr/local/cuda-10.1/lib64
00019:    relion_run_motioncorr --version
00020:   Protocol failed: Command ' relion_run_motioncorr --version ' returned non-zero exit status 127.
00021:   FAILED: _convertInputStep, step 1, time 2022-03-02 15:23:21.929385
00022:   *** Last status is failed
00023:   ------------------- PROTOCOL FAILED (DONE 1/1611)

**Desktop (please complete the following information):**
 - Scipion version: 3.0.1
 - Relion plugin version 4.0 and 3.1
 
Thanks for your attention. 

Adrià.

**Comment by Adriaj95** [comment]
Yes, sure.

File 'Runs/001951_ProtRelionMotioncor/logs/run.stderr' doesn't existFile 'Runs/001951_ProtRelionMotioncor/logs/run.stderr' doesn't exist00001:   /bin/sh: relion_run_motioncorr: command not found
00002:   Traceback (most recent call last):
00003:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
00004:       self._run()
00005:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 252, in _run
00006:       resultFiles = self._runFunc()
00007:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _runFunc
00008:       return self._func(*self._args)
00009:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/relion/protocols/protocol_motioncor.py", line 227, in _convertInputStep
00010:       self.runJob("relion_run_motioncorr --version", "", numberOfMpi=1)
00011:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1441, in runJob
00012:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00013:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
00014:       process.runJob(log, programName, params,
00015:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 52, in runJob
00016:       return runCommand(command, env, cwd)
00017:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 67, in runCommand
00018:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
00019:     File "/opt/miniconda/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
00020:       raise CalledProcessError(retcode, cmd)
00021:   subprocess.CalledProcessError: Command ' relion_run_motioncorr --version ' returned non-zero exit status 127.
00022:   Protocol failed: Command ' relion_run_motioncorr --version ' returned non-zero exit status 127.

**Comment by azazellochg** [comment]
Thanks, that looks pretty obvious, you do not have relion binaries installed or properly configured. Have a look at https://github.com/scipion-em/scipion-em-relion#installation

**Comment by Adriaj95** [comment]
Thank you very much. Tomorrow we will try to fix it.

**Comment by azazellochg** [comment]
@Adriaj95 has this been sorted?

**Comment by Adriaj95** [comment]
Hello, no. Our informatician fixed something that made work some protocols from relion but 2D doesn't work. It appears another error.

I attatch de run.stderr. Sorry for replying late, I coundn't have access to the computer until now. 

00001:   Traceback (most recent call last):
00002:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
00003:       self._run()
00004:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 252, in _run
00005:       resultFiles = self._runFunc()
00006:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _runFunc
00007:       return self._func(*self._args)
00008:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/relion/protocols/protocol_base.py", line 889, in runRelionStep
00009:       self.runJob(self._getProgram(), params)
00010:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1441, in runJob
00011:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00012:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
00013:       process.runJob(log, programName, params,
00014:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 52, in runJob
00015:       return runCommand(command, env, cwd)
00016:     File "/opt/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 67, in runCommand
00017:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
00018:     File "/opt/miniconda/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
00019:       raise CalledProcessError(retcode, cmd)
00020:   subprocess.CalledProcessError: Command ' mpirun -np 3  `which relion_refine_mpi` --i Runs/002405_ProtRelionClassify2D/input_particles.star --particle_diameter 256.5 --ctf  --zero_mask  --K 50 --center_classes  --norm  --scale  --o Runs/002405_ProtRelionClassify2D/extra/relion --oversampling 1 --flatten_solvent  --tau2_fudge 2.0 --iter 25 --offset_range 5.0 --offset_step 2.0 --psi_step 12.0 --dont_combine_weights_via_disc  --preread_images  --pool 3 --gpu "0:1"  --j 1' returned non-zero exit status 137.
00021:   Protocol failed: Command ' mpirun -np 3  `which relion_refine_mpi` --i Runs/002405_ProtRelionClassify2D/input_particles.star --particle_diameter 256.5 --ctf  --zero_mask  --K 50 --center_classes  --norm  --scale  --o Runs/002405_ProtRelionClassify2D/extra/relion --oversampling 1 --flatten_solvent  --tau2_fudge 2.0 --iter 25 --offset_range 5.0 --offset_step 2.0 --psi_step 12.0 --dont_combine_weights_via_disc  --preread_images  --pool 3 --gpu "0:1"  --j 1' returned non-zero exit status 137.

**Comment by azazellochg** [comment]
Hello @Adriaj95 , exit code 137 is "out of memory" error.
