### ISSUE TITLE
Problem installing relion-4.0 plugin

### ISSUE THREAD

**Issue by olofsvensson** [scipion-em/scipion-em-relion#331]
Hi,

I'm trying to install the latest Scipion version "v3.0.10 - Eugenius - 3.0.19 (core)" on an Ubuntu 20.04 computer.

Everything has worked fine till I tried to install the Relion plugin via the plugin manager:

```
02387:   Building relion-4.0 ...
02388:     Skipping command: wget -nv -c -O /home/svensson/scipion/software/em/void.tgz.part http://scipion.cnb.csic.es/downloads/scipion/software/em/void.tgz
02389:   mv -v /home/svensson/scipion/software/em/void.tgz.part /home/svensson/scipion/software/em/void.tgz
02390:     All targets exist.
02391:   cd /home/svensson/scipion/software/em
02392:   mkdir /home/svensson/scipion/software/em/relion-4.0
02393:     Skipping command: tar -xf void.tgz -C relion-4.0
02394:     All targets exist.
02395:   cd /home/svensson/scipion/software/em/relion-4.0
02396:   echo "We do not provide Relion binaries for 4.0beta release. You should skip binaries installation and read https://relion.readthedocs.io/en/release-4.0/Installation.html for instructions."
```

Any help is appreciated on how to install the Relion plugin.

Thanks,

Olof

**Comment by pconesa** [comment]
I've transfer the issue. I've also explained by email to @olofsvensson that "theoretically" this is not a error, but technically it is, thus the "stacktrace".

It basically, is telling you, in a dramatic way, to install relion 4 manually.

**Comment by pconesa** [comment]
Why don't we just remove the "binaries definition for relion4". And have a proper message, even a "validateInstallation" implementation, noting that the installation is missing?

**Comment by azazellochg** [comment]
Hi both, I've created a PR which will fix this.
