### ISSUE TITLE
relion - ctf refinement visualization

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#35]
Hi,

  In relion 3.0 tutorial, ctf refinement section sSors suggesto to check 3 items -two images and a pdf file-
 (I attach the corresponding paragraph to this email) Current implementation of ctf refinement in Scipion does not shown any of these three items. I volunteer to modify Analyze if it OK with you

===================
You can analyse the refined defoci by selecting the logfile.pdf file from the
Display: button on the GUI. Can you spot micrographs where the ice layer was
not horizontal?
The beamtilt estimate is stored in the file CtfRefine/job024/beamtilt_0.txt;
the image with the phase differences from which this estimate was derived can
be displayed using:
relion_display --i CtfRefine/job024/beamtilt_delta-phase_per-pixel.mrc --scale 3 &
and the model fitted through it can be displayed using:
relion_display --i CtfRefine/job024/beamtilt_delta-phase_lin-fit.mrc --scale 3 &
If the beamtilt was significant, this image will show one side of the circle blacker
and one side whiter than the rest. In this case, the beamtilt was estimated
to be approximately 0 mrad in X and -0.2 mrad in Y. At the resolution of
these data, that does not make a significant difference. One could re-run the
Ctf refinement job without beam-tilt estimation. We chose just to move on with
it instead.

**Comment by azazellochg** [comment]
Hi @rmarabini you can go ahead and modify the results. :)

**Comment by rmarabini** [comment]
OK

**Comment by delarosatrevin** [comment]
Thanks @rmarabini! Yes, feel free to go ahead and modify it to provide this results more easily. I didn't because lack of time...and their are still accessible from the browser of this run. Please, as usual, create a PR with the modifications.

**Comment by delarosatrevin** [comment]
This issue is being addressed in #48
