### ISSUE TITLE
subtract projection error

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#365]
reported by @EstrellaFG 
```
I am using subtract projection protocol from relion 4.0 plugin in Scipion, but when I use as input particles the ones produced by xmipp 
 - add noise particles I got the error that I attach in a screenshot. I have use these particles in other protocols and they worked fine. I 
have also tried relion subtract projection with other input an it works too. Moreover, if I take this same particles with noise and then 
I add ctf (by using xmipp - simulate ctf protocol) and I use the result as input particles for relion subtract projection it works too.
Could you please have a look?

To reproduce it just run xmipp-add noise particles and then use them as input to relion subtract projection.
```
![Screenshot from 2022-10-05 12-35-29](https://user-images.githubusercontent.com/6952870/194328354-9200c637-6680-4518-b293-6819b73e951d.png)

**Comment by azazellochg** [comment]
@EstrellaFG since you didnt provide full output I cant reproduce it. 
![image](https://user-images.githubusercontent.com/6952870/194332171-95c0d60f-3d83-4e26-ad5f-a6b4de9f6b14.png)

**Comment by azazellochg** [comment]
from the error I can only guess your particles that you input to xmipp protocol are not good - they might not have acquisition.opticsgroupinfo

**Comment by EstrellaFG** [comment]
Hi,
you can find the particles to reproduce the issue in this link: https://we.tl/t-xyOBoqta29. Moreover I have tried to execute protocol "relion - assign optics groups" with these particles and it falied also so I have sent you the logs by email.

**Comment by azazellochg** [comment]
Thank you! I'll have a look later this week.

**Comment by azazellochg** [comment]
Hi, as I still cant reproduce this, can you update your emtable to the latest version?
`scipion pip install -U emtable`

**Comment by EstrellaFG** [comment]
The particles have no ctf as they are the output of "xmipp3 - create gallery" (which creates projections from a given volume). I can not choose swiching off the ctf correction as I am selecting "Star from Relion protocol" option. I will try to update emtable, thanks.

**Comment by azazellochg** [comment]
you cannot select start from relion protocol as it does not accept particles, but a protocol.

**Comment by EstrellaFG** [comment]
Yes, you are right, that was from another trial with auto-refine as input, sorry for the mistake. In this case I use as input the particles, select No in "Star from Relion protocol" and No in "Do CTF correction"
