### ISSUE TITLE
relion.tests.test_workflow_relion3 fails if gctf is not installed

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#38]
relion.tests.test_workflow_relion3 imports gctf and fails if not available.

  I suggest to change:

from 
  gctf.protocols import ProtGctf
to 
   importFromPlugin('gctf.protocols', 'ProtGctf')

In this way we will not get an error message if we execute

  scipion test --show

**Comment by delarosatrevin** [comment]
Please change this together with other modification you are proposing.
