### ISSUE TITLE
ewald sphere

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#389]
H @azazellochg,

I use a lot the "ewald sphere" correction in  the reconstruction protocol. In practice this requires to add in the "extra parameters" line a string similar to:

--ewald --mask_diameter 1100 --sectors 2 --width_mask_edge 5 --reverse_curvature

Will it be OK if I modified the protocol "protocol_reconstruction.py" and add an extra tab with the following content?

        int ewald_section = parser.addSection("Ewald-sphere correction options");
	do_ewald = parser.checkOption("--ewald", "Correct for Ewald-sphere curvature (developmental)");
	mask_diameter  = textToFloat(parser.getOption("--mask_diameter", "Diameter (in A) of mask for Ewald-sphere curvature correction", "-1."));
	width_mask_edge = textToInteger(parser.getOption("--width_mask_edge", "Width (in pixels) of the soft edge on the mask", "3"));
	is_reverse = parser.checkOption("--reverse_curvature", "Try curvature the other way around");
	newbox = textToInteger(parser.getOption("--newbox", "Box size of reconstruction after Ewald sphere correction", "-1"));
	nr_sectors = textToInteger(parser.getOption("--sectors", "Number of sectors for Ewald sphere correction", "2"));
	skip_mask = parser.checkOption("--skip_mask", "Do not apply real space mask during Ewald sphere correction");
	skip_weighting = parser.checkOption("--skip_weighting", "Do not apply weighting during Ewald sphere correction");

**Comment by azazellochg** [comment]
Very good idea @rmarabini , I've made a PR for you to review
