### ISSUE TITLE
Allow 'relion - extract particles' to input particles

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-relion#41]
This way, it will be closer to the implementation in Relion GUI. Moreover, it is true that almost in all cases that we use 'scipion - extract coordinates', we run an extract after it. So, we are always using two protocols for this. It would be good to have a viewer showing particles in the Micrographs.

**Comment by azazellochg** [comment]
I think we are missing more options than just this:
![Screenshot_20190815_102103](https://user-images.githubusercontent.com/6952870/63085853-6f740080-bf46-11e9-9ae5-eb70ecc550ed.png)

**Comment by delarosatrevin** [comment]
Will be addressed in a more general issue
