### ISSUE TITLE
Installation of RELION Plugin Stalls

### ISSUE THREAD

**Issue by jpellman** [scipion-em/scipion-em-relion#418]
**Describe the bug**

Hi, 

When I attempt to install the RELION plugin via the plugin manager, the installation does not appear to progress / seems to stall out at some point.  I can see that some of the RELION binaries/artifacts have been produced, but it does not appear that all of them are present in the build output directory.  Is this a known issue?  Are only certain RELION binaries supposed to be generated?

I've noticed that even though the plugin manager window indicates that installation is proceeding, no `cmake`, `make` or `g++` commands are running.

**To Reproduce**
1. Go to plugin manager
2. Install RELION plug in
3. Wait indefinitely.

**Expected behavior**
The RELION plugin should finish installation in a timely manner and all RELION binaries should be present.

**Logs**
There are no logs produced that I can find- is there a log somewhere that stores the contents of stdout/stderr during the build process?  The plugin manager shows nothing.

**Additional context**

We're using Ubuntu 22.04 with CUDA 11.4.3 libraries for our userland.

**Comment by pconesa** [comment]
Hi @jpellman m sorry about this.

Latest relion version downloads many files and creates a conda environment the takes some time.

Best thing to do is to use the command line:

scipion3 install -p scipion-em-relion

You'll see everything in the terminal and avoid the "freeze" in the plugin manager.


Alternatively, if you already have relion5 installed you can pass to the command --noBin to skip relion installation and link it using the config file:

https://scipion-em.github.io/docs/release-3.0.0/docs/scipion-modes/linking-existing-software.html


Let us know how it goes....

**Comment by azazellochg** [comment]
In my case, the conda env creation took 10 min:
```
gsharov@lvx-0855:~/test/relion$ conda env create -f environment.yml -y
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
                                                                                                                                                                                             
Preparing transaction: done                                                                                                                                                                  
Verifying transaction: done                                                                                                                                                                  
Executing transaction: done                                                                                                                                                                  
Installing pip dependencies: ...
```
Nevertheless, it has finished successfully. I'm afraid Scipion can't do anything about this. Pablo has suggested other options above.
