### ISSUE TITLE
Error executing  "relion - 3D autorefine" with the option "use blush regularization" set to "yes".

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#420]
I had the following problem when executing protocol "relion - 3D autorefine" with the option "use blush regularization" set to "yes".  
This is not a Scipion bug, I just report the bug and the fix because other users may face the same problem.

Set up: scipion installed in account "user2" and executed in account "user1".

  The protocol seems to write in directory "~user2/.cache/torch/hub/checkpoints/relion_blush/" since user1 cannot write here the protocol fails. 
Fix: modify write permissions of the directory ".cache/torch/hub/checkpoints/relion_blush/ (and the corresponding fathers)

=====================
Error message

00001:   Traceback (most recent call last):
00002:     File "<string>", line 1, in <module>
00003:     File "/home/user2/miniconda/envs/relion-5.0/lib/python3.10/site-packages/relion_blush/command_line.py", line 275, in main
00004:       model, model_path = install_and_load_model(
00005:     File "/home/user2/miniconda/envs/relion-5.0/lib/python3.10/site-packages/relion_blush/util.py", line 814, in install_and_load_model
00006:       os.makedirs(dest_dir, exist_ok=True)
00007:     File "/home/user2/miniconda/envs/relion-5.0/lib/python3.10/os.py", line 215, in makedirs
00008:       makedirs(head, exist_ok=exist_ok)
00009:     File "/home/user2/miniconda/envs/relion-5.0/lib/python3.10/os.py", line 215, in makedirs
00010:       makedirs(head, exist_ok=exist_ok)
00011:     File "/home/user2/miniconda/envs/relion-5.0/lib/python3.10/os.py", line 215, in makedirs
00012:       makedirs(head, exist_ok=exist_ok)
00013:     File "/home/user2/miniconda/envs/relion-5.0/lib/python3.10/os.py", line 225, in makedirs
00014:       mkdir(name, mode)
**00015:   **PermissionError: [Errno 13] Permission denied: '/home/user2/.cache/torch'****
00016:

**Comment by azazellochg** [comment]
Hi @rmarabini , you need to set TORCH_HOME in the config to a shared file system that all users can access.
