### ISSUE TITLE
Relon_export_coordinate issue

### ISSUE THREAD

**Issue by Ankushcreatedroid** [scipion-em/scipion-em-relion#428]
After sub particle extraction I was trying to export coordinate to relion but export coordinate xmipp cannot send coordinates around different particles from same micrographs and only keeping one set of particle coordinates for each micrograph. 

Please suggest any solution that resolve this parsing issue

**Comment by azazellochg** [comment]
Hello @Ankushcreatedroid 
What I could understand from your description is that you have run some localrec protocol that creates subparticle coordinates. Is that correct? Then you tried to run "relion  - export coordinates" and got fewer coordinates than expected, right? I think I can reproduce your issue using the workflow below :

![image](https://github.com/user-attachments/assets/12292c22-1f29-476a-b437-8c0e460064d2)

**Comment by Ankushcreatedroid** [comment]
yes exactly i wanted to explain sorry for the delayed response

**Comment by Ankushcreatedroid** [comment]
So you can see if a Micrograph has 3 particles and I defined 5 fold vertices of 3 particles in icosahedral symmetry then each particles should have 12 coordinates written for 3 particles for same micrograph and when I export coordinate in relion I am getting either one of the two particles respective 12 coordinate written in coord.star file

**Comment by azazellochg** [comment]
I have pushed a fix to devel branch, could you pull and test it?

**Comment by Ankushcreatedroid** [comment]
Yes for sure i will try and let you know in this thread

**Comment by Ankushcreatedroid** [comment]
actually i am new to github can you help how can i get the fixed code to test

**Comment by azazellochg** [comment]
Great

**Comment by Ankushcreatedroid** [comment]
One more query is that during my sub particle extraction which used cryosparc patch aligned coordinate and when after defining subparticle and exporting those coordinates to relion. The relion extraction is not pointing the coordinate as of the particles position. Did you faced it before if yes how can i fix this

**Comment by azazellochg** [comment]
Hi, I dont use cryosparc so I will need more details about the problem.
Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: ***@***.***

**Comment by Ankushcreatedroid** [comment]
Steps performed in detail

1) imported particle in scipion from a non-uniform refinement in icosahedral symmetry 

2) define 3fold subparticle coordinate in scipion local rec protocol 

3) further tried using relion export coordinate for export coordinate to relion for particle extraction 

4) written a customised.star file where rln micrograph was pointing towards motion correction from relion and rln coordinates from step 

But when i tried to extract using customeized.star file in relion coordinate are pointing in totally different location

**Comment by azazellochg** [comment]
Hi, finding a dataset to check this will take me some time. Relion does not modify input coordinates when doing export. I suggest you [open an issue in the localrec plugin](https://github.com/scipion-em/scipion-em-localrec) to see if anyone has done a workflow like this before

**Comment by azazellochg** [comment]
@Ankushcreatedroid I've had another look using empiar-10117. As far as I understand, once the subparticles are defined, their micname is removed and their new coordinates are relative to the input particles and have no relation with the micrographs (except micId). So you cannot go back to original mics once you start working with subparicles. Better to check with localrec developers.

To check if your coordinates for subparticles are correct, you can just click "Analyze Results" of the define subparticles protocol. It will show you the coords on top of the input particles:
![image](https://github.com/user-attachments/assets/6d271f5e-7dff-4e9a-b358-d74a8c393fd5)

**Comment by Ankushcreatedroid** [comment]
Ok thank you for the direction i check with the developers
