### ISSUE TITLE
missing option in relion 2D

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#56]
In scipiopn 1.2, relion 2D classify used to have, in tab Optimization, an expert option that allowed to select a mask. Is oK if I put it back or is there any reason why this option has been removed?

**Comment by delarosatrevin** [comment]
I have check scipion 1.2 (relion3 and relion2) and I can't find this mask option that you are missing in expert mode. 

Moreover, I checked the Relion 3 GUI and I can't find this neither, so, unless there is a good reason for this option, I would prefer to stick to the original package.

**Comment by rmarabini** [comment]
Hi,

Ok, Let us summarize this issue report before closing it

1) Dr Benito complained about this missing  parameter

2) I checked that the parameter is missing. In the attachment you may see
the Optimization tab for relion 2D classificatio for Dioclecian (right) and
for Claudius (left). All the options are the default ones and no input
particles have been selected. As you can see in one case by default the
option reference mask is available and in the other case the option is not
available.

3) Now that I look the problem more carefully I realize that this option
does not make sense in 2D (I will ask Dr Benito why he used it). So the new
version in which the option is not available is the correct one

    cheers

   Roberto

**Comment by azazellochg** [comment]
it was [removed](https://github.com/scipion-em/scipion-em-relion/commit/e792e08a83167783116881f75d019e7a66511806#diff-5bc6585e6fc771a87441f614eccb0eeb) by @delarosatrevin in by mistake I assume. It must be there (https://github.com/I2PC/scipion/issues/836). I'll put it back.

**Comment by rmarabini** [comment]
Hi again,

   This is Dr Benito comments about the mask  (sorry for the Spanish)

".. en el 2D también se pueden poner máscaras para focalizar la
clasificacion en un zona. Yo lo he hecho bastantes veces, con las
hélices por ejemplo pongo un rectángulo."


In relion 1.2.1 the relevant code is:
===================================
if self.IS_3D:
form.addParam('referenceMask', PointerParam,
pointerClass='VolumeMask',
label='Reference mask (optional)', allowsNull=True,
help='A volume mask containing a (soft) mask with '
'the same dimensions as the reference(s), '
'and values between 0 and 1, with 1 being 100% '
'protein and 0 being 100% solvent. The '
'reconstructed reference map will be multiplied '
'by this mask. If no mask is given, a soft '
'spherical mask based on the <radius> of the '
'mask for the experimental images will be '
'applied.\n\n'
'In some cases, for example for non-empty '
'icosahedral viruses, it is also useful to use '
'a second mask. Check _Advaced_ level and '
'select another volume mask')
......
else:
form.addParam('referenceMask', PointerParam, pointerClass='Mask',
label='Reference mask (optional)', allowsNull=True,
expertLevel=LEVEL_ADVANCED,
help='User-provided mask for the references ('
'default is to use spherical mask with '
'particle_diameter)')

====================

So it seems that it was possible to provide a mask for the 2D case while
now the "else" is gone. So... may I put back
---
else:
form.addParam('referenceMask', PointerParam, pointerClass='Mask',
label='Reference mask (optional)', allowsNull=True,
expertLevel=LEVEL_ADVANCED,
help='User-provided mask for the references ('
'default is to use spherical mask with '
'particle_diameter)') -- Roberto

**Comment by delarosatrevin** [comment]
@rmarabini , this options has been restored by @azazellochg in a PR. I don't remember any good reason why I removed, so is very likely it was a mistake as @azazellochg suggested. I will take a look at the PR and merge it. 

Say thanks to Dr. Martín-Bonito for reporting this.
