### ISSUE TITLE
missing block name

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#58]
https://github.com/scipion-em/scipion-em-relion/blob/16b4b4f01781a3a26c6fb5c7c1a67d180e068a79/relion/convert/metadata.py#L230

**Comment by delarosatrevin** [comment]
Hi @azazellochg, Can you provide more details of this issue? One example star file that cause it?

**Comment by azazellochg** [comment]
Hi @delarosatrevin it's just a missing substitution :)

**Comment by delarosatrevin** [comment]
Can you be more explicit? I can fix it tomorrow.

**Comment by azazellochg** [comment]
raise Exception("%s block was not found" % dataStr)
