### ISSUE TITLE
motioncor does not work without patches

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#59]
local_motion_model table does not exist if user selects <=2 patches and then relion runs only global motion correction. We need to fix output step for this case

**Comment by delarosatrevin** [comment]
Either I'm having a dejavú or we have lost code..because I think that I already fixed this. In any case,I will take a look.

**Comment by azazellochg** [comment]
@delarosatrevin It's interesting, because it works if I select 1x1 patches, but not 2x2. Output star file is exactly the same

**Comment by delarosatrevin** [comment]
Is issue the same as #58?

**Comment by delarosatrevin** [comment]
It seems to me that Relion also do global alignment only when using 2x2...I have fixed this here: 109a3a7cfd03
