### ISSUE TITLE
motioncor creates empty output folder in the project folder

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#60]
The correct output folder is in tmp/movie_######/output. The one in project folder should not exist..

**Comment by delarosatrevin** [comment]
This is a bit weird...first, because the runJob is executed with cwd=movieTmpFolder...
Second, I swear that I got this 'output' folder at the project level...but now that I'm checking it, it is not generated anymore. 

Can you double check this issue in branch 'protocol-fixes'??

**Comment by azazellochg** [comment]
Yes, I still have this folder

**Comment by delarosatrevin** [comment]
Found it!...fixed in 59ec20b
