### ISSUE TITLE
move export prots to export section

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#61]
![Screenshot_20190522_215727](https://user-images.githubusercontent.com/6952870/58208438-a1295280-7cdc-11e9-8082-404b0aba7135.png)

**Comment by delarosatrevin** [comment]
Export protocols added to protocols.conf in the "Exports" section. (commit fa80973)

![Screenshot from 2019-05-25 23-52-11](https://user-images.githubusercontent.com/8441688/58374936-5ad82b80-7f48-11e9-9482-da7ad0d7295f.png)
