### ISSUE TITLE
motioncorr failed output step

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#62]
Master branch, running with 24 threads, 1 MPI, do dose-weighting=yes, save non-dose weighted=no
```
00434:   STARTED: createOutputStep, step 26
00435:     2019-05-23 20:13:32.084982
00436:   Traceback (most recent call last):
00437:     File "/net/nfs1/public/EM/Scipion/scipion-2.0.0/pyworkflow/protocol/protocol.py", line 186, in run
00438:       self._run()
00439:     File "/net/nfs1/public/EM/Scipion/scipion-2.0.0/pyworkflow/protocol/protocol.py", line 237, in _run
00440:       resultFiles = self._runFunc()
00441:     File "/net/nfs1/public/EM/Scipion/scipion-2.0.0/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00442:       return self._func(*self._args)
00443:     File "/net/nfs1/public/EM/Scipion/scipion-2.0.0/pyworkflow/em/protocol/protocol_align_movies.py", line 114, in createOutputStep
00444:       output = self.outputMicrographs
00445:   AttributeError: 'ProtRelionMotioncor' object has no attribute 'outputMicrographs'
00446:   Protocol failed: 'ProtRelionMotioncor' object has no attribute 'outputMicrographs'
00447:   FAILED: createOutputStep, step 26
```

**Comment by azazellochg** [comment]
basically the core protocol it looks for outputMicrographs which are not produced since we have only dose-weighted ones

**Comment by delarosatrevin** [comment]
This is a bug in the base protocol, so in scipion/pyworkflow/em. 
The is a function _createOutputMicrographs that should return True if micrographs will be created (as well as _createOutputWeightedMicrographs), but this is not respected when trying to access the outputMicrographs attribute, it should be checked that _createOutputMicrographs returns true before that. 

I will open a bug in the core repo and keep this open as a reminder.

**Comment by delarosatrevin** [comment]
In the meantime that the base class is fixed...I have re-implemented the createOutputFunction in this protocol, so it will not fail. (commit 79b2c22)
