### ISSUE TITLE
motioncor not using mpi?

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#63]
1) Figure out if mpi can be used by relion
2) at the moment all MPI processes are running on each input movie sequentially.

**Comment by delarosatrevin** [comment]
Hi @azazellochg,
I think the Relion program can use both MPI and threads....
I think our protocol is "using MPI", but not in a very smart way...as you said...all go to the same movie.

There are some bigger problems here:
* In PARALLEL_STEPS mode, we can't combine threads and MPI in our Scipion parallel implementation
* The batch mode is not implemented for motion correction protocols, in which case we could make a better use of MPI and threads

**Comment by delarosatrevin** [comment]
I would like to consider a more general solution to this problem...so I will remove the r1.0.5 label from this issue and postpone it for another release.

**Comment by delarosatrevin** [comment]
Will be addressed in a more general issue
