### ISSUE TITLE
Exports to relion star files may be broken

### ISSUE THREAD

**Issue by rsanchezgarc** [scipion-em/scipion-em-relion#77]
Apparently, exported coordinates (e.g. export particles) are not being properly understood by relion.
The header of the relion star files seems to have changed and thus, it is no longer able to recognize it. 

scipion export example: 

\# XMIPP_STAR_1 * 
# 
data_Particles
loop_
 _rlnEnabled
 _rlnCoordinateX
 _rlnCoordinateY
 _rlnMicrographName

Relion example file
\# RELION; version 3.0-beta-2

data_

loop_
_rlnCoordinateX #1
_rlnCoordinateY #2
_rlnAutopickFigureOfMerit #3
_rlnClassNumber #4
_rlnAnglePsi #5

RELION 3.1 should be checked

**Comment by azazellochg** [comment]
@rsanchezgarc I have no problems importing the star file with the following header in relion 3.0.6:
```
# XMIPP_STAR_1 * 
# 
data_Particles
loop_
 _rlnEnabled
 _rlnCoordinateX
 _rlnCoordinateY
 _rlnAutopickFigureOfMerit
 _rlnClassNumber
 _rlnAnglePsi
 _rlnMicrographName
 _rlnMicrographId
 _rlnImageId
 _rlnImageName
 _rlnDefocusU
 _rlnDefocusV
 _rlnDefocusAngle
 _rlnAmplitudeContrast
 _rlnSphericalAberration
 _rlnVoltage
 _rlnMagnification
 _rlnOriginalParticleName
 _rlnDetectorPixelSize
```

**Comment by azazellochg** [comment]
Alright, you are trying to import coordinates into relion using an exported particles star file. This will never work. You need to have star coord file per each mic.
