### ISSUE TITLE
relion postprocess command is wrong

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#83]
scipion: diocletian
scipion-em-relion: devel updated on (19-Jun-2019)

If I run relion postprocess the following command is lunched:

relion_postprocess --autob_lowres 10.0 --randomize_at_fsc 0.8 --auto_bfac  --filter_edge_width 2 --o Runs/005302_ProtRelionPostprocess/extra/postprocess --i Runs/005302_ProtRelionPostprocess/input/relion --angpix 2.84 --autob_highres 0.0 --mask Runs/005302_ProtRelionPostprocess/input/input_mask.mrc

This command returns the error message:

   ERROR: 
   The input filename does not contain 'half1' or 'half2'

but if I run in a terminal  the command
     /usr/local/relion/build/bin/relion_postprocess  --autob_lowres 10.0 --randomize_at_fsc 0.8 --auto_bfac  --filter_edge_width 2 --o Runs/005302_ProtRelionPostprocess/extra/postprocess --i Runs/005302_ProtRelionPostprocess/input/relion_half1_class001_unfil.mrc  --angpix 2.84 --autob_highres 0.0 --mask Runs/005302_ProtRelionPostprocess/input/input_mask.mrc

the process finish. NOTE the difference is the value of the argument "--i"

So I guess the half1_class001_unfil is needed

**Comment by delarosatrevin** [comment]
What version of Relion are you using inside and outside Scipion? I think there was a change about the --i form one version to another...maybe a bug was introduced. Please report the Relion versions to better track this.

**Comment by rmarabini** [comment]
Relion version:

  RELION_VERSION "3.0.5"

**Comment by delarosatrevin** [comment]
@rmarabini What version or the scipion-em-relion plugin are you using (from pypi, branch?). I'm using the devel branch of it + relion 3.0.6...and the command line generated looks more like the second one that you have mentioned and it works. Can you check if in your config file you have relion pointing to 2.x or older version?

**Comment by rmarabini** [comment]
Hi,

It is not clear to my what version of scipion-em-relion I am using. scipion
GUI reports that I am using version 1.0.3 but I believe that I am using the
code I cloned from git. This code is a devel branch with
hash 2c46ae824862510d5db402d96efdc324a4cda429, and version '1.0.5' (or at
least this is what I see in the setup.py file). If I search for files
called "*relion*" in scipion directory I
get ./software/lib/python2.7/site-packages/scipion-em-relion.egg-link, this
file contains the line "/usr/local/Plugins/scipion-em-relion" that is the
place where I have the scipion-em-relion clone with version 1.0.5.

   roberto

**Comment by delarosatrevin** [comment]
What Relion version/install do you have in ~/.config/scipion/scipion.conf
file?

I'm not sure about what is the exact version of the plugin in the
conditions that you are describing.

**Comment by rmarabini** [comment]
src/macros.h:#define RELION_VERSION "3.0.5"

**Comment by delarosatrevin** [comment]
Not that, the one (location) in the scipion.conf file.

**Comment by rmarabini** [comment]
In scipion.conf I have

   RELION_HOME = /usr/local/relion/build

if I execute
/usr/local/relion/build/bin/relion_refine --version

I get

RELION version: 3.0.5
Precision: BASE=double, CUDA-ACC=single

**Comment by delarosatrevin** [comment]
Hum...that might be the issue...the Relion binary version is "parsed" from
the link name...so,
I would recommend you to have a soft link: scipion/software/em/relion-3.0
-> /usr/local/relion/build
And in your scipion.conf:
RELION_HOME = %(EM_ROOT)s/relion-3.0
In that way, the version 3.0 will be recognized and the proper command for
postprocess generated.

**Comment by rmarabini** [comment]
You were right, rename relion directory from relion to relion-3.0 fixed the
problem ;-).

**Comment by delarosatrevin** [comment]
Ok, good to know that it is solved now. I'm closing this issue then.
