### ISSUE TITLE
relion_refine3d and continue -> prints an error message in summary

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#85]
Scipion: dioclecian
relion: 3.0.6
relion plugin: devel  16b4b4f01781a3a26c6fb5c7c1a67d180e068a79

If a relion_refine 3D continues another relion_refine 3D an ERROR  message like the following one is printed in summary:

[1;31mFileName::isMetaData: File: 'Runs/005878_ProtRelionRefine3D/extra/relion_it016_half1_model.star' does not exist [0m

The problem is in the summary routine:

```
    def _summaryNormal(self):
        """ Should be overwritten in subclasses to 
        return summary message for NORMAL EXECUTION. 
        """
        summary = []
        if not hasattr(self, 'outputVolume'):
            summary.append("Output volume not ready yet.")
            it = self._lastIter()
            if it >= 1:
                row = md.getFirstRow('model_general@' +
                                     self._getFileName('half1_model',
                                                       iter=it))
                resol = row.getValue("rlnCurrentResolution")
                summary.append("Current resolution: *%0.2f A*" % resol)
```
In particular in the line
```

            if it >= 1:
                row = md.getFirstRow('model_general@' +
                                     self._getFileName('half1_model',
                                                       iter=it))

```
since _getFileName returns a path to the current protocol but until the first iteration is done the file is in the previous protocol (the one we want to continue from).

 An easy fix would be to modify 

`if it >= 1:
`
by

`if it >= 1 and  it > self._getContinueIter():
`

alternatively self.continueRun.get()._getFileName() may be used but then the logic is more complex.

I am willing to create a pull request with the solution you like better.

**Comment by azazellochg** [comment]
Thank you, @rmarabini !
