### ISSUE TITLE
Import particles when particles files names are repeated but on different folders does not work fine

### ISSUE THREAD

**Issue by ldelcano** [scipion-em/scipion-em-relion#87]
When importing particles from relion that are located in different folders with names repeated among them, results are wrong (particles.sqlite is created with all particles but links on extra file only point to some of them).
First, particle location should be unique on sqlite as it is done when importing from files in Scipion images.py (importImagesStep):
            uniqueFn = self._getUniqueFileName(fileName)
Second, copyOrLink in relion import should create unique files.

**Comment by azazellochg** [comment]
@delarosatrevin I'm afraid to touch any import funcs, do you mind having a look? I think maybe we could put an equivalent of getUniqueFileName https://github.com/scipion-em/scipion-em-relion/blob/devel/relion/convert/convert.py#L660 here, but I might be wrong.

**Comment by delarosatrevin** [comment]
It is almost one year since this issue. @ldelcano Can you check if the issue still persist? There has been some changes since that time.

**Comment by ldelcano** [comment]
I can verify in scipion2 but not in scipion3.

**Comment by delarosatrevin** [comment]
Not in Scipion3 means that you haven't tested or that it is not happening? 
Could you try to test in Scipion3?

**Comment by ldelcano** [comment]
I am no longer developing in scipion and I haven't even tried to install scipion3 so it might take me long time to do it, which I do not have... but I will talk to Pablo and if it is easy I can do it.

**Comment by delarosatrevin** [comment]
Thanks @ldelcano , I will close this issue until further notice.

**Comment by ldelcano** [comment]
I am afraid this problem is still happening. I have created a star file with 4 particles (spi), splitted in two folders where names are equal and when I import them, all appear in particles.sqlite but links on extra folder are only 2. See attached files.
[Test.txt](https://github.com/scipion-em/scipion-em-relion/files/4763302/Test.txt)
![Screenshot_scipion](https://user-images.githubusercontent.com/12271385/84358416-6afc9080-abc7-11ea-9ef5-a3f5c535b787.png)

**Comment by azazellochg** [comment]
I've checked with relion 3.1 star file and it works:
```
.:
total 12
drwxr-xr-x 2 azazello azazello 4096 Nov 29 18:30 folder1
drwxr-xr-x 2 azazello azazello 4096 Nov 29 18:30 folder2
-rw-r--r-- 1 azazello azazello 3862 Nov 29 18:53 relion_it017_data.star

./folder1:
total 87560
-rw-r--r-- 1 azazello azazello 40371200 Nov 29 18:30 20170629_00037_frameImage_shiny.mrcs
-rw-r--r-- 1 azazello azazello 49284096 Nov 29 18:29 20170629_00044_frameImage_shiny.mrcs

./folder2:
total 87560
-rw-r--r-- 1 azazello azazello 40371200 Nov 29 18:30 20170629_00037_frameImage_shiny.mrcs
-rw-r--r-- 1 azazello azazello 49284096 Nov 29 18:30 20170629_00044_frameImage_shiny.mrcs
```
[relion_it017_data.star.txt](https://github.com/scipion-em/scipion-em-relion/files/5612673/relion_it017_data.star.txt)
![image](https://user-images.githubusercontent.com/6952870/100550874-e684f380-3274-11eb-88c7-a8779064714c.png)

For relion 3.0 or older star file format this doesn't work. The problem appears in https://github.com/scipion-em/scipion-em-relion/blob/master/relion/convert/dataimport.py#L289. It was agreed that we cant support <3.1 code anymore so I don't plan to fix this. @delarosatrevin do you want to volunteer or we close this?
