### ISSUE TITLE
Suggestion to change some default values

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-relion#9]
Reported by Jaime:
Image is for a 2D classification run with "fill with 0" (in optimsation) , which is the default value in Scipion, (right image) and with "fill with random noise" (left image) which is the default value for relion. He rather have "fill with random noise" as default value.
![image](https://user-images.githubusercontent.com/785633/48200036-32972f80-e35e-11e8-8b7e-bd52415ffdca.png)

**Comment by delarosatrevin** [comment]
I will take a look at this. We should always try to keep the same defaults as in the original package...unless a big argument against it.

**Comment by delarosatrevin** [comment]
Hi I have checked in Relion 2 (and 3) and in both, that option has a default value of "Mask individual particles with zeros?" = Yes in Relion....and we have also this default. See attached image. 
![2d-relion-scipion](https://user-images.githubusercontent.com/8441688/48350821-9f753700-e688-11e8-9143-eb53e355da07.png)

So, I vote for closing this issue.

**Comment by josuegbl** [comment]
Me too, although my vote is not valid if I aligned with you, @delarosatrevin :tongue:
