### ISSUE TITLE
rlnOpticsGroup

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#94]
Upon import we have new fields called _rlnOpticsGroupName #1 and _rlnOpticsGroup #2. First one is a string (defined in GUI), second is a number (auto-numbered by relion code). Example of star file is below:
![Screenshot_20190827_191311](https://user-images.githubusercontent.com/6952870/63797046-26855a00-c8ff-11e9-92fc-5642ab6738d0.png)

Imagine if you have a Relion3.1 project and you import two sets of movies with different opticsGroupNames you will have rlnOpticsGroup: 1 and 2. 

Current implementation in scipion/relion repos (relion31 branches):
New acquisition parameter is set during import movies: opticsGroupName (+ beam tilt, defect file and mtf file, but that’s not a problem). It is a string that has to be specified by the user in the import movies GUI.

In relion plugin in every protocol, in convertInputStep, all opticsGroupNames are collected from particles/mics/movies into a dict and opticsGroup number is assigned to each of dict items, so we get:
opticsGroupName = “mysupergroup1” : opticsGroup = 1
opticsGroupName = “huge beam tilt” : opticsGroup = 2

Update: it looks like Relion will rename and renumber the groups in the star file unless you have >1 group in one star file. So, if you have a single group in a star file, it’s number must be 1, otherwise: Warning: the optics groups in img_h1_i2432_movie_00000_Jul16_06.45.38_input.star are not in the right order - renaming them now

**Comment by delarosatrevin** [comment]
@azazellochg I think we need to get into Relion 3.1 without depending on changes in the core. 
So, I propose that we introduce a protocol 'relion - assign optic groups' that set these fields for movies, micrographs or particles. In that way, we could move on and it should be ready if some of the properties are already set in the import, what do you think?

**Comment by dmaluenda** [comment]
I agree with the idea of having a protocol to assign metadata. Talking about beam tilt with @pconesa and @cossorzano, we also arrived at this approach.

In this way, all is on the plugin side, but not in the core.

**Comment by delarosatrevin** [comment]
Thanks for the feedback @dmaluenda. I really like the idea of keeping specific information in plugins and not the core.

**Comment by azazellochg** [comment]
@delarosatrevin subsets after assigning groups into Acquisition are not working..
